/**
 * @file app/api/sessions/[id]/portal/route.ts
 *
 * Routes: GET | POST | PUT /api/sessions/[id]/portal
 *
 * Manages the speaker portal artifact for a session. A speaker portal is a
 * rich, multi-section document generated for the guest speaker. It is more
 * extensive than the speaker brief and includes a context narrative, curated
 * student questions, engagement signals, class history, and recommendations.
 * Portals have two phases: pre-session (generated here) and post-session
 * (generated by lib/ai/speakerPortalPostSession.ts after debrief completion).
 *
 * GET  — retrieves the stored portal record (null if not yet generated).
 * POST — generates and persists the portal via Gemini (idempotent: returns
 *         the existing portal if one already exists for this session).
 * PUT  — saves professor edits to the portal without regenerating it. Edits
 *         are stored in `editedContent` separate from the AI original.
 *
 * Auth:        Required on all methods — 401 if not logged in; 404 if session
 *              belongs to another user.
 * DB calls:    getCurrentUser(), getSessionById(), getSpeakerPortal(),
 *              insertSpeakerPortal(), updateSpeakerPortalEdits(),
 *              getSessionAnalysis(), getClassInsights(), fetchInsightsInput(),
 *              session_themes (admin client)
 * AI calls:    generateSpeakerPortalContent() from lib/ai/speakerPortal.ts (Gemini)
 * Error util:  extractErrorMessage() from lib/utils/errors.ts
 *
 * PII note: analysis and class-insights data are sanitized via
 * sanitizeAnalysis() before being sent to Gemini so no student-identifying
 * information leaves the server.
 */

import { NextResponse } from 'next/server'
import { getCurrentUser } from '@/lib/db/users'
import { getSessionById } from '@/lib/db/sessions'
import { getSpeakerPortal, insertSpeakerPortal, updateSpeakerPortalEdits } from '@/lib/db/speakerPortals'
import { getSessionAnalysis } from '@/lib/db/sessionAnalyses'
import { getClassInsights, fetchInsightsInput } from '@/lib/db/classInsights'
import { createAdminClient } from '@/lib/supabase/server'
import { generateSpeakerPortalContent } from '@/lib/ai/speakerPortal'
import { extractErrorMessage } from '@/lib/utils/errors'
import type { SanitizedAnalysis, SanitizedClassInsights } from '@/lib/ai/speakerBrief'
import type { SessionAnalysis, QuestionFeedback } from '@/types'

// force-dynamic ensures auth cookies are read on every request, never cached
/**
 * What it does: Exports a constant string, 'force-dynamic'.
 * Why it is used: This Next.js configuration ensures that the API route handler is treated as a dynamic request.
 * Important implementation details: Setting 'force-dynamic' prevents the route from being cached and forces re-evaluation on every request, which is essential for ensuring that authentication cookies are read and processed correctly for each incoming request.
 */
export const dynamic = 'force-dynamic'

/**
 * Strips student PII from a full `SessionAnalysis` before sending it to
 * Gemini. Only aggregate, anonymised fields are forwarded to the AI.
 *
 * @param analysis - Full per-session analysis from the `session_analyses` table
 * @returns Sanitized subset safe to include in an AI generation prompt
 */
/**
 * What it does: Transforms a comprehensive `SessionAnalysis` object into a `SanitizedAnalysis` object.
 * Why it is used: This function is crucial for data privacy. It removes any Personally Identifiable Information (PII) from the session analysis data before it is sent to an external AI model (Gemini) for content generation, complying with privacy standards.
 * Important implementation details: It selectively maps `theme_clusters` to include only aggregate fields (`name`, `question_count`, `top_question`) and forwards other high-level, anonymized fields like `tensions`, `suggestions`, `blind_spots`, and `sentiment`. Any fields that might contain specific student-level details are deliberately omitted.
 */
function sanitizeAnalysis(analysis: SessionAnalysis): SanitizedAnalysis {
  return {
    theme_clusters: analysis.theme_clusters.map((c) => ({
      name: c.name,
      question_count: c.question_count,
      top_question: c.top_question,
    })),
    tensions: analysis.tensions,
    suggestions: analysis.suggestions,
    blind_spots: analysis.blind_spots,
    sentiment: analysis.sentiment,
  }
}

/**
 * GET /api/sessions/[id]/portal
 *
 * Returns the stored speaker portal record for the session, or null if one
 * has not been generated yet. The UI uses this to decide whether to show the
 * "Generate" button or the portal preview.
 *
 * @param _request  - Unused
 * @param params.id - Session UUID from the URL path segment
 * @returns JSON `{ portal: SpeakerPortal | null }` or `{ error: string }`
 *          with status 401 / 404 / 500.
 *
 * @see lib/db/speakerPortals.ts — `getSpeakerPortal()`
 */
/**
 * What it does: Handles HTTP GET requests to retrieve an existing speaker portal record for a specified session.
 * Why it is used: The frontend UI uses this endpoint to determine whether a speaker portal has already been generated for a given session. This dictates whether to display a 'Generate Portal' button or the actual portal content to the user.
 * Important implementation details:
 * 1. Authentication: It first authenticates the user using `getCurrentUser()`, returning a 401 Unauthorized if no user is found.
 * 2. Authorization (Ownership Check): It verifies that the authenticated user owns the session specified by `params.id`. A 404 Not Found is returned for non-existent or unowned sessions to prevent information leakage.
 * 3. Data Retrieval: It fetches the speaker portal record using `getSpeakerPortal(params.id)`.
 * 4. Response: Returns the `SpeakerPortal` object if found, or `null` if one has not been generated yet, wrapped in a JSON response. Includes robust error handling and logging.
 */
export async function GET(
  _request: Request,
  { params }: { params: { id: string } }
) {
  try {
    // Auth check — returns null if Supabase cookie is absent or expired
    const user = await getCurrentUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    // Ownership check — 404 rather than 403 to avoid leaking session existence
    const session = await getSessionById(params.id)
    if (!session || session.userId !== user.id) {
      return NextResponse.json({ error: 'Session not found' }, { status: 404 })
    }

    const portal = await getSpeakerPortal(params.id)
    return NextResponse.json({ portal })
  } catch (err) {
    console.error('[/api/sessions/[id]/portal] GET', err)
    return NextResponse.json({ error: extractErrorMessage(err) }, { status: 500 })
  }
}

/**
 * POST /api/sessions/[id]/portal
 *
 * Generates a speaker portal using Gemini and persists it. Idempotent — if a
 * portal already exists for the session it is returned without a Gemini call.
 *
 * Generation inputs assembled before the AI call:
 *   - Theme titles from `session_themes` (ordered by theme_number)
 *   - Sanitized session analysis (PII stripped) from `session_analyses`
 *   - Sanitized class insights (PII stripped) from `class_insights`
 *   - Debrief history for past sessions (speaker ratings, feedback, surprise
 *     moments) — provides historical context for the portal's "past visits"
 *     section. The current session is excluded from this history.
 *   - Session date, speaker name, file count, and raw session output
 *
 * @param _request  - No request body required
 * @param params.id - Session UUID from the URL path segment
 * @returns JSON `{ portal: SpeakerPortal }` or `{ error: string }`
 *          with status 401 / 404 / 500.
 *
 * @remarks
 * `debriefHistory` is sourced via `fetchInsightsInput()` which returns an
 * extended session list. Sessions without a debrief rating and the current
 * session are filtered out before passing to Gemini.
 *
 * @see lib/ai/speakerPortal.ts — `generateSpeakerPortalContent()`
 * @see lib/db/speakerPortals.ts — `getSpeakerPortal()`, `insertSpeakerPortal()`
 * @see lib/db/classInsights.ts — `getClassInsights()`, `fetchInsightsInput()`
 */
/**
 * What it does: Handles HTTP POST requests to generate a new speaker portal for a specific session using an AI model (Gemini) and then persists it to the database.
 * Why it is used: This endpoint orchestrates the creation of the detailed speaker portal, synthesizing various data points (session themes, analysis, class insights, historical debriefs) into a comprehensive summary for the speaker.
 * Important implementation details:
 * 1. Authentication & Authorization: Similar to GET, it performs user authentication and session ownership checks.
 * 2. Idempotency: Before generating, it checks if a portal already exists for the session. If so, it returns the existing portal without re-calling the AI, optimizing resource usage.
 * 3. Data Aggregation: It gathers diverse inputs including session themes (ordered), sanitized session analysis, sanitized class insights, and filtered debrief history from past sessions.
 * 4. PII Sanitization: Crucially, `sanitizeAnalysis` and a similar process for `classInsights` are applied to ensure no PII is sent to the AI.
 * 5. AI Generation: It calls `generateSpeakerPortalContent()` from `lib/ai/speakerPortal` to interact with Gemini, providing all the prepared inputs.
 * 6. Persistence: The AI-generated content is then saved to the database via `insertSpeakerPortal()`.
 * 7. Admin Client: An admin Supabase client is used for ancillary data reads (e.g., themes) after ownership is verified, bypassing Row Level Security (RLS) for efficiency.
 * 8. Error Handling: Catches and logs errors, returning appropriate JSON responses.
 */
export async function POST(
  _request: Request,
  { params }: { params: { id: string } }
) {
  try {
    // Auth check
    const user = await getCurrentUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    // Ownership check
    const session = await getSessionById(params.id)
    if (!session || session.userId !== user.id) {
      return NextResponse.json({ error: 'Session not found' }, { status: 404 })
    }

    // Idempotency check — return the existing portal without calling Gemini again
    const existing = await getSpeakerPortal(params.id)
    if (existing) {
      return NextResponse.json({ portal: existing })
    }

    // Admin client bypasses RLS for ancillary reads; ownership already verified
    const supabase = createAdminClient()

    // Fetch theme titles ordered by position in the session output
    const { data: themeRows, error: themeErr } = await supabase
      .from('session_themes')
      .select('theme_title')
      .eq('session_id', params.id)
      .order('theme_number', { ascending: true })
    if (themeErr) throw new Error(`Failed to fetch themes: ${themeErr.message}`)
    const themes = (themeRows ?? []).map((r) => r.theme_title as string)

    // Fetch cached session analysis
    const analysis = await getSessionAnalysis(params.id)

    // Fetch class insights
    const classInsights = await getClassInsights(user.id)

    // Fetch debrief history for past speaker insights (section 5)
    const insightsInput = await fetchInsightsInput(user.id)
    const debriefHistory = insightsInput.sessions
      .filter(s => s.debriefRating !== null && s.sessionId !== params.id)
      .map(s => {
        // These fields may exist on extended InsightsInput versions
        const extended = s as typeof s & { debriefSpeakerFeedback?: string; debriefSurpriseMoments?: string }
        return {
          speakerName: s.speakerName,
          rating: s.debriefRating!,
          speakerFeedback: extended.debriefSpeakerFeedback ?? '',
          homeRunCount: s.debriefHomeRunCount,
          surpriseMoments: extended.debriefSurpriseMoments ?? '',
        }
      })

    // Sanitize data
    const sanitizedAnalysis: SanitizedAnalysis | null = analysis
      ? sanitizeAnalysis(analysis)
      : null

    const sanitizedInsights: SanitizedClassInsights | null = classInsights
      ? {
          narrative: classInsights.narrative,
          qualityTrend: classInsights.qualityTrend,
          topThemes: classInsights.topThemes.map((t) => ({
            title: t.title,
            sessionCount: t.sessionCount,
          })),
        }
      : null

    const sessionDate = new Date(session.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })

    // Generate portal content via Gemini
    const content = await generateSpeakerPortalContent({
      speakerName: session.speakerName,
      professorName: 'Professor Drennen',
      sessionDate,
      fileCount: session.fileCount,
      themes,
      sessionOutput: session.output,
      analysis: sanitizedAnalysis,
      classInsights: sanitizedInsights,
      debriefHistory: debriefHistory.length > 0 ? debriefHistory : null,
    })

    // Persist to DB
    const portal = await insertSpeakerPortal(params.id, user.id, content)

    return NextResponse.json({ portal })
  } catch (err) {
    console.error('[/api/sessions/[id]/portal] POST', err)
    return NextResponse.json({ error: extractErrorMessage(err) }, { status: 500 })
  }
}

/**
 * What it does: Handles HTTP PUT requests to update the `editedContent` field of an existing speaker portal record.
 * Why it is used: This endpoint allows users (e.g., professors or speakers) to manually edit or refine the AI-generated speaker portal content, providing a mechanism for personalization and corrections.
 * Important implementation details:
 * 1. Authentication & Authorization: It enforces user authentication and verifies session ownership to ensure only authorized users can modify a portal.
 * 2. Request Body: It expects the `editedContent` (a string or `null`) in the request body.
 * 3. Database Update: It calls `updateSpeakerPortalEdits()` to persist the provided `editedContent` to the database for the specified session ID.
 * 4. Nullable Content: `editedContent` can be `null`, allowing users to clear any previously saved manual edits.
 * 5. Response: Returns a success indicator or an error message based on the outcome of the update operation.
 */
export async function PUT(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const user = await getCurrentUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const session = await getSessionById(params.id)
    if (!session || session.userId !== user.id) {
      return NextResponse.json({ error: 'Session not found' }, { status: 404 })
    }

    const body = await request.json()
    const { editedContent } = body

    await updateSpeakerPortalEdits(params.id, editedContent ?? null)

    return NextResponse.json({ success: true })
  } catch (err) {
    console.error('[/api/sessions/[id]/portal] PUT', err)
    return NextResponse.json({ error: extractErrorMessage(err) }, { status: 500 })
  }
}
