/**
 * @file lib/db/reports.ts
 *
 * CRUD for semester reports — on-demand AI-generated documents covering
 * executive summary, theme evolution, student engagement, question quality,
 * and more across a set of sessions.
 *
 * Reports are generated by `lib/ai/reportAgent.ts` and stored permanently for
 * retrieval and export.  They are immutable after creation — re-generating
 * produces a new row rather than updating an existing one.
 *
 * Table: semester_reports
 *
 * Called by:
 *   - app/api/reports/generate/route.ts       (POST — insertReport)
 *   - app/api/reports/[id]/route.ts           (GET — getReportById)
 *   - app/api/reports/[id]/download/route.ts  (GET — getReportById for export)
 *
 * Read by (portfolio context, admin client):
 *   - lib/db/portfolioShares.ts → getPortfolioReports, getPortfolioReportById
 *   - app/api/portfolio/[token]/reports/route.ts
 *   - app/api/portfolio/[token]/reports/[reportId]/route.ts
 */

import { createAdminClient, createClient } from '@/lib/supabase/server'
import type { SemesterReport, SemesterReportRow, ReportConfig, ReportContent } from '@/types'

/**
 * Map a raw `semester_reports` database row to the camelCase domain type.
 */
/**
 * What it does: Maps a raw `semester_reports` database row to the camelCase domain type.
 * Why it is used: This function is used to transform data fetched directly from the database, which typically uses snake_case, into a more idiomatic TypeScript object structure (camelCase) for use within the application's domain logic.
 * Important implementation details: It directly maps specific fields from `SemesterReportRow` to `SemesterReport`, converting `user_id` to `userId`, `session_ids` to `sessionIds`, and `created_at` to `createdAt`.
 */
function rowToReport(row: SemesterReportRow): SemesterReport {
  return {
    id: row.id,
    userId: row.user_id,
    title: row.title,
    config: row.config,
    content: row.content,
    sessionIds: row.session_ids,
    createdAt: row.created_at,
  }
}

/**
 * Persist a newly generated semester report.
 *
 * Reports are INSERT-only — there is no update path.  Re-generating a report
 * for the same semester creates a new row with a new `id`, preserving the
 * history of previous generations.
 *
 * @param userId     - UUID of the owning professor
 * @param title      - Human-readable title (e.g. "Fall 2025 Semester Report")
 * @param config     - `ReportConfig` specifying which sections were included
 * @param content    - Full `ReportContent` JSONB payload from the AI agent
 * @param sessionIds - Array of session UUIDs included in this report
 * @returns The newly inserted `SemesterReport` including its auto-assigned `id`
 * @throws {Error} If the insert fails
 *
 * Client: createAdminClient() — bypasses RLS
 *         (report generation runs server-side after validating auth; admin
 *          client avoids potential RLS policy edge cases during INSERT)
 * Called by: app/api/reports/generate/route.ts (POST)
 */
/**
 * What it does: Persists a newly generated semester report into the database.
 * Why it is used: This function is crucial for storing the results of AI-driven report generation, ensuring that reports are saved and can be retrieved later.
 * Important implementation details: Reports are INSERT-only; there is no update path. Re-generating a report for the same semester creates a new row with a new `id`, preserving the history of previous generations. It uses `createAdminClient()` to bypass Row Level Security (RLS) during the insert, which is appropriate as report generation runs server-side after validating user authentication. It returns the newly inserted `SemesterReport` and throws an `Error` if the insert fails.
 */
export async function insertReport(
  userId: string,
  title: string,
  config: ReportConfig,
  content: ReportContent,
  sessionIds: string[]
): Promise<SemesterReport> {
  const supabase = createAdminClient()
  const { data, error } = await supabase
    .from('semester_reports')
    .insert({
      user_id: userId,
      title,
      config,
      content,
      session_ids: sessionIds,
    })
    .select()
    .single()

  if (error) throw new Error(`Failed to insert report: ${error.message}`)
  return rowToReport(data as SemesterReportRow)
}

/**
 * Fetch a single report by its primary key.
 * Returns `null` (without throwing) if not found or if RLS blocks access.
 *
 * @param id - UUID of the `semester_reports` row
 * @returns `SemesterReport` or `null`
 *
 * Client: createClient() — RLS enforced (professor can only read their own reports)
 * Called by: app/api/reports/[id]/route.ts (GET),
 *            app/api/reports/[id]/download/route.ts (GET)
 */
/**
 * What it does: Fetches a single semester report by its primary key (ID).
 * Why it is used: This allows for the retrieval of specific reports when a user wants to view or download a particular report.
 * Important implementation details: It returns `null` (without throwing an error) if the report is not found or if RLS blocks access. It uses `createClient()`, meaning RLS is enforced, ensuring that a professor can only read their own reports. The fetched row is mapped to the `SemesterReport` domain type using `rowToReport`.
 */
export async function getReportById(id: string): Promise<SemesterReport | null> {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('semester_reports')
    .select('*')
    .eq('id', id)
    .maybeSingle()

  if (error || !data) return null
  return rowToReport(data as SemesterReportRow)
}

/**
 * List all reports for the authenticated professor, newest first.
 *
 * RLS automatically filters results to the current user, so no explicit
 * `user_id` filter is needed here.
 *
 * @returns Array of `SemesterReport` objects ordered by `created_at DESC`
 *          (empty array if none exist or on error)
 *
 * Client: createClient() — RLS enforced
 * Called by: app/(app)/reports/page.tsx (via server component)
 */
/**
 * What it does: Lists all semester reports associated with the currently authenticated professor.
 * Why it is used: This function provides the functionality to display a history or overview of all generated reports for the logged-in user, typically on a dedicated reports page.
 * Important implementation details: RLS automatically filters the results to the current user, so no explicit `user_id` filter is needed in the query. Reports are ordered by `created_at` in descending order (newest first). It returns an empty array if no reports exist or if an error occurs. Each retrieved database row is mapped to the `SemesterReport` domain type using `rowToReport`.
 */
export async function listReports(): Promise<SemesterReport[]> {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('semester_reports')
    .select('*')
    .order('created_at', { ascending: false })

  if (error || !data) return []
  return data.map((row: SemesterReportRow) => rowToReport(row))
}
