/**
 * @file lib/db/sessionShares.ts
 *
 * Share tokens for public session links — creates, revokes, and resolves
 * token-based access to session data and cached analyses without requiring
 * recipients to be authenticated.
 *
 * Tables touched:
 *   - session_shares  (primary CRUD)
 *   - sessions        (cross-join for getSessionByShareToken)
 *   - session_analyses (cross-join for getSessionAnalysisByShareToken)
 *
 * Called by:
 *   - app/api/sessions/[id]/share/route.ts  (GET — getSessionShare, POST — enableSessionShare / revokeSessionShare)
 *
 * Read by (public, no auth):
 *   - app/api/shared/[token]/route.ts           (getSessionByShareToken)
 *   - app/api/shared/[token]/analysis/route.ts  (getSessionAnalysisByShareToken)
 */

import { createAdminClient, createClient } from '@/lib/supabase/server'
import type { Session, SessionShareRow, SessionShare, SessionAnalysis, SessionRow } from '@/types'
import { rowToSession } from '@/lib/utils/transforms'

/**
 * Map a raw `session_shares` database row to the camelCase domain type.
 */
/** Maps a raw `session_shares` database row object (snake_case) to the corresponding `SessionShare` domain type (camelCase). This transformation ensures consistency in the application's data representation, making it easier to work with `sessionShare` objects throughout the frontend and backend logic. It's a standard utility for data serialization/deserialization. */
function rowToSessionShare(row: SessionShareRow): SessionShare {
  return {
    id: row.id,
    sessionId: row.session_id,
    shareToken: row.share_token,
    createdAt: row.created_at,
  }
}

/**
 * Get the share record for a session that the authenticated professor owns.
 * Returns `null` (silently) if no share exists or if RLS blocks access.
 *
 * @param sessionId - UUID of the session
 * @returns `SessionShare` or `null`
 *
 * Client: createClient() — RLS enforced (professor can only see their own shares)
 * Called by: app/api/sessions/[id]/share/route.ts (GET)
 */
/** Retrieves an existing `SessionShare` record for a given session ID, specifically for the currently authenticated professor. It utilizes a `createClient()` instance, which enforces Supabase Row Level Security (RLS), ensuring that a professor can only access share records for sessions they own. If no share exists or RLS prevents access, it returns `null` silently, as the caller typically interprets a missing share as the session simply "not being shared". */
export async function getSessionShare(sessionId: string): Promise<SessionShare | null> {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('session_shares')
    .select('*')
    .eq('session_id', sessionId)
    .maybeSingle()

  // Silently return null on error — the caller treats missing share as "not shared"
  if (error) return null
  return data ? rowToSessionShare(data as SessionShareRow) : null
}

/**
 * Enable sharing for a session — inserts a new row whose `share_token` is
 * auto-generated by the database DEFAULT (usually `gen_random_uuid()`).
 *
 * @param sessionId - UUID of the session to share
 * @param userId    - UUID of the owning professor (used for future revocation)
 * @returns The newly created `SessionShare` including the generated token
 * @throws {Error} If the insert fails (e.g. duplicate — session already shared)
 *
 * Client: createAdminClient() — bypasses RLS (needed to insert on behalf of user)
 * Called by: app/api/sessions/[id]/share/route.ts (POST)
 */
/** Enables sharing for a specific session by inserting a new record into the `session_shares` table. The `share_token` is automatically generated by the database (usually a UUID). This function uses `createAdminClient()` to bypass RLS, which is necessary because the professor's `user_id` is passed explicitly for the insert operation. It returns the newly created `SessionShare` object, including the generated token, and throws an error if the insertion fails (e.g., if the session is already shared). */
export async function enableSessionShare(sessionId: string, userId: string): Promise<SessionShare> {
  const supabase = createAdminClient()
  const { data, error } = await supabase
    .from('session_shares')
    .insert({ session_id: sessionId, user_id: userId })
    .select()
    .single()

  if (error) throw new Error(`Failed to enable sharing: ${error.message}`)
  return rowToSessionShare(data as SessionShareRow)
}

/**
 * Revoke sharing for a session — deletes the share row, immediately
 * invalidating any previously distributed token.
 *
 * @param sessionId - UUID of the session
 * @param userId    - UUID of the owning professor (prevents cross-user revocation)
 * @throws {Error} If the delete fails
 *
 * Client: createAdminClient() — bypasses RLS
 * Called by: app/api/sessions/[id]/share/route.ts (POST with `enabled: false`)
 */
/** Revokes sharing for a given session by deleting its corresponding record from the `session_shares` table. This action immediately invalidates any previously distributed share tokens for that session. It uses `createAdminClient()` to bypass RLS and ensures that only the session's owner (`userId`) can revoke the share, preventing unauthorized revocation. An error is thrown if the deletion fails. */
export async function revokeSessionShare(sessionId: string, userId: string): Promise<void> {
  const supabase = createAdminClient()
  const { error } = await supabase
    .from('session_shares')
    .delete()
    .eq('session_id', sessionId)
    .eq('user_id', userId)  // scoped to owner so no professor can revoke another's share

  if (error) throw new Error(`Failed to revoke sharing: ${error.message}`)
}

/**
 * Resolve a share token to the full session record.
 * Used by the public share viewer — no authentication required.
 *
 * Performs two sequential queries:
 *  1. Validate the token exists in `session_shares` → get `session_id`
 *  2. Fetch the full session row from `sessions`
 *
 * @param token - The UUID share token from the public URL
 * @returns The full `Session` domain object, or `null` if token is invalid
 *
 * Client: createAdminClient() — bypasses RLS (public route, no auth cookie)
 * Read by: app/api/shared/[token]/route.ts
 */
/** Resolves a given `share_token` to the full `Session` record. This function is designed for public access, allowing unauthenticated users to view shared session content. It performs two sequential database queries: first, it validates the `share_token` in `session_shares` to obtain the `session_id`, and then it fetches the complete `SessionRow` from the `sessions` table using that ID. It uses `createAdminClient()` to bypass RLS as it's intended for public routes without an active user session. Returns `null` if the token is invalid or the session cannot be found. */
export async function getSessionByShareToken(token: string): Promise<Session | null> {
  const supabase = createAdminClient()

  // Step 1: verify the share token exists and retrieve the linked session_id
  const { data: share, error: shareError } = await supabase
    .from('session_shares')
    .select('session_id')
    .eq('share_token', token)
    .maybeSingle()

  if (shareError || !share) return null

  // Step 2: fetch the full session now that the token is confirmed valid
  const { data: session, error: sessionError } = await supabase
    .from('sessions')
    .select('*')
    .eq('id', share.session_id)
    .single()

  if (sessionError || !session) return null
  return rowToSession(session as SessionRow)
}

/**
 * Resolve a share token to the cached Gemini analysis for that session.
 * Callers should handle `null` gracefully (analysis may not be generated yet).
 *
 * Performs two sequential queries:
 *  1. Validate token → get `session_id`
 *  2. Fetch cached analysis from `session_analyses`
 *
 * @param token - The UUID share token from the public URL
 * @returns The cached `SessionAnalysis`, or `null` if token invalid or analysis absent
 *
 * Client: createAdminClient() — bypasses RLS (public route, no auth cookie)
 * Read by: app/api/shared/[token]/analysis/route.ts
 */
/** Retrieves the cached Gemini analysis for a session identified by a `share_token`. This function is similar to `getSessionByShareToken` in its public-facing nature, requiring no authentication. It first validates the `share_token` to find the associated `session_id`, then queries the `session_analyses` table for the cached analysis. Callers must handle the case where the analysis might be `null`, as the analysis might not have been generated yet even if the session is valid and shared. It uses `createAdminClient()` to bypass RLS for public access. */
export async function getSessionAnalysisByShareToken(token: string): Promise<SessionAnalysis | null> {
  const supabase = createAdminClient()

  // Step 1: validate share token
  const { data: share, error: shareError } = await supabase
    .from('session_shares')
    .select('session_id')
    .eq('share_token', token)
    .maybeSingle()

  if (shareError || !share) return null

  // Step 2: fetch cached analysis (may be null if Gemini hasn't run yet)
  const { data, error } = await supabase
    .from('session_analyses')
    .select('analysis')
    .eq('session_id', share.session_id)
    .maybeSingle()

  if (error || !data) return null
  return data.analysis as SessionAnalysis
}
