/**
 * @file lib/db/stories.ts
 *
 * CRUD for semester narrative stories — AI-generated human-readable accounts
 * of a semester's arc, structured in 5 sections (opening, thematic journey,
 * student engagement, growth moments, closing reflection).
 *
 * Unlike `reports.ts` (metrics-focused, insert-only), stories are upserted
 * per semester — regenerating a story for the same semester updates the
 * existing row rather than creating a duplicate.  Section content can be
 * individually updated after generation.
 *
 * Table: semester_stories
 *
 * Called by:
 *   - app/api/stories/generate/route.ts   (POST — upsertStory)
 *   - app/api/stories/[id]/route.ts       (GET — getStoryById)
 *   - app/api/stories/[id]/download/route.ts  (GET — getStoryById for export)
 *   - app/(app)/stories/[id]/page.tsx     (via GET /api/stories/[id])
 *   - app/(app)/semesters/page.tsx        (via getStoryBySemesterId to show existing story)
 */

import { createAdminClient, createClient } from '@/lib/supabase/server'
import type { SemesterStory, SemesterStoryRow, StorySection } from '@/types'

/**
 * Map a raw `semester_stories` database row to the camelCase domain type.
 */
/**
 * Map a raw `semester_stories` database row to the camelCase domain type.
 *
 * What it does: Transforms a database row object, typically retrieved directly from Supabase, into a structured application-level `SemesterStory` object.
 * Why it is used: This function acts as a crucial data transformation layer, converting the snake_case naming convention commonly found in database schemas (`user_id`, `created_at`) into the camelCase convention (`userId`, `createdAt`) used throughout the TypeScript application. This ensures consistency and better readability within the application's domain model.
 * Important implementation details: It performs a direct, one-to-one mapping of properties, ensuring that all necessary fields are transferred and correctly named for use in the application.
 */
function rowToStory(row: SemesterStoryRow): SemesterStory {
  return {
    id: row.id,
    userId: row.user_id,
    semesterId: row.semester_id,
    title: row.title,
    sections: row.sections,
    sessionIds: row.session_ids,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }
}

/**
 * Insert or replace the narrative story for a semester.
 *
 * There is a unique index on `semester_id`, so only one story can exist per
 * semester.  This function checks for an existing row manually (rather than
 * using a single upsert) so it can return the full updated row reliably across
 * Supabase's upsert + `select()` edge cases.
 *
 * @param userId     - UUID of the owning professor
 * @param semesterId - UUID of the semester this story belongs to
 * @param title      - Story title generated by the AI agent
 * @param sections   - Array of 5 `StorySection` objects (narrative content)
 * @param sessionIds - Session UUIDs that were included as input to the agent
 * @returns The saved `SemesterStory` row
 * @throws {Error} If the insert or update fails
 *
 * Client: createAdminClient() — bypasses RLS
 *         (story generation runs server-side; admin client avoids RLS edge cases on upsert)
 * Called by: app/api/stories/generate/route.ts (POST)
 */
/**
 * Insert or replace the narrative story for a semester.
 *
 * What it does: Creates a new `semester_stories` record or updates an existing one based on the `semester_id`. It handles the full lifecycle of a story's initial creation or re-generation.
 * Why it is used: This is the primary function for persisting AI-generated narrative stories to the database. It ensures that only one story exists per semester by either inserting a new story or updating the content of an existing one, making it central to the story generation process.
 * Important implementation details:
 * 1.  **Client**: Uses `createAdminClient()` to bypass Row Level Security (RLS). This is critical because story generation runs on the server, and an admin client ensures that the operation can proceed regardless of the current user's RLS permissions, preventing potential issues with partial unique indexes on `semester_id` and ensuring reliable upsert behavior.
 * 2.  **Manual Upsert Logic**: Rather than relying on a single Supabase `upsert` call, this function explicitly checks for an existing story using `select().eq().maybeSingle()`. If a story is found, it performs an `update`; otherwise, it performs an `insert`. This manual approach is necessary because Supabase's `upsert` helper has known limitations with partial unique indexes (like the one expected on `semester_id`), which could lead to inconsistent behavior with `select()` after upsert.
 * 3.  **Error Handling**: Throws an `Error` if the insert or update operation fails, providing clear feedback to the calling context.
 * 4.  **Timestamp Management**: Automatically updates the `updated_at` timestamp when an existing story is modified.
 */
export async function upsertStory(
  userId: string,
  semesterId: string,
  title: string,
  sections: StorySection[],
  sessionIds: string[]
): Promise<SemesterStory> {
  const supabase = createAdminClient()

  // Check for an existing story on this semester to decide INSERT vs UPDATE.
  // A true upsert on `semester_id` is not used because the conflict target
  // is a partial unique index, which Supabase's upsert helper doesn't support cleanly.
  const { data: existing } = await supabase
    .from('semester_stories')
    .select('id')
    .eq('semester_id', semesterId)
    .maybeSingle()

  if (existing) {
    // Story already exists — update content and bump updated_at
    const { data, error } = await supabase
      .from('semester_stories')
      .update({
        title,
        sections,
        session_ids: sessionIds,
        updated_at: new Date().toISOString(),
      })
      .eq('id', existing.id)
      .select()
      .single()
    if (error) throw new Error(`Failed to update story: ${error.message}`)
    return rowToStory(data as SemesterStoryRow)
  }

  // No existing story — insert a new row
  const { data, error } = await supabase
    .from('semester_stories')
    .insert({
      user_id: userId,
      semester_id: semesterId,
      title,
      sections,
      session_ids: sessionIds,
    })
    .select()
    .single()
  if (error) throw new Error(`Failed to insert story: ${error.message}`)
  return rowToStory(data as SemesterStoryRow)
}

/**
 * Fetch a single story by its primary key.
 * Returns `null` (without throwing) if not found or if RLS blocks access.
 *
 * @param id - UUID of the `semester_stories` row
 * @returns `SemesterStory` or `null`
 *
 * Client: createClient() — RLS enforced
 * Called by: app/api/stories/[id]/route.ts (GET),
 *            app/api/stories/[id]/download/route.ts (GET)
 */
/**
 * Fetch a single story by its primary key.
 *
 * What it does: Retrieves a specific `SemesterStory` record from the database using its unique identifier (`id`).
 * Why it is used: This function is used to fetch a particular story when its ID is known, for example, when a user clicks on a link to view a specific story, or when an API route needs to retrieve a story for download or detailed display.
 * Important implementation details:
 * 1.  **Client**: Uses `createClient()` which enforces Row Level Security (RLS). This is vital for client-facing data retrieval, ensuring that users can only access stories they are authorized to view according to the defined database policies.
 * 2.  **Null Return**: Returns `null` if no story is found with the given `id` or if RLS blocks access, rather than throwing an error. This allows consuming code to gracefully handle cases where a story might not exist or be inaccessible.
 * 3.  **Data Transformation**: Leverages `rowToStory` to convert the raw database row into the application's `SemesterStory` domain type.
 */
export async function getStoryById(id: string): Promise<SemesterStory | null> {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('semester_stories')
    .select('*')
    .eq('id', id)
    .maybeSingle()

  if (error || !data) return null
  return rowToStory(data as SemesterStoryRow)
}

/**
 * Fetch the story for a specific semester (at most one exists per semester).
 * Returns `null` (without throwing) if no story has been generated yet.
 *
 * @param semesterId - UUID of the semester
 * @returns `SemesterStory` or `null`
 *
 * Client: createClient() — RLS enforced
 * Called by: app/(app)/semesters/page.tsx (to show existing story link)
 */
/**
 * Fetch the story for a specific semester (at most one exists per semester).
 *
 * What it does: Retrieves the unique `SemesterStory` associated with a given `semesterId`.
 * Why it is used: This function is essential for scenarios where the context is a semester, and the application needs to determine if a story exists for it or to display that specific story. For instance, a dashboard might show a link to the story only if one has been generated for a particular semester.
 * Important implementation details:
 * 1.  **Client**: Uses `createClient()`, which enforces Row Level Security (RLS). This ensures that only users authorized to view stories for the specified semester can retrieve the data.
 * 2.  **Null Return**: Returns `null` if no story has been generated for the given `semesterId` or if RLS blocks access, providing a clean way to check for the presence of a story without requiring error handling.
 * 3.  **Uniqueness**: Relies on the unique index on `semester_id` in the database to guarantee that at most one story will be returned.
 * 4.  **Data Transformation**: Utilizes `rowToStory` to map the database record to the application's `SemesterStory` domain type.
 */
export async function getStoryBySemesterId(semesterId: string): Promise<SemesterStory | null> {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('semester_stories')
    .select('*')
    .eq('semester_id', semesterId)
    .maybeSingle()

  if (error || !data) return null
  return rowToStory(data as SemesterStoryRow)
}

/**
 * Replace the section content of an existing story (e.g. after professor edits).
 *
 * Only `sections` and `updated_at` are changed — metadata like `title`,
 * `session_ids`, and `semester_id` are left intact.
 *
 * @param id       - UUID of the `semester_stories` row to update
 * @param sections - New array of `StorySection` objects
 * @throws {Error} If the update fails
 *
 * Client: createAdminClient() — bypasses RLS
 * Called by: app/api/stories/[id]/route.ts (PATCH)
 */
/**
 * Replace the section content of an existing story (e.g. after professor edits).
 *
 * What it does: Updates only the `sections` array and the `updated_at` timestamp of an existing `semester_stories` record.
 * Why it is used: This function provides a mechanism for users (typically professors) to edit and save changes to the narrative content of an AI-generated story. It allows for targeted updates without affecting other story metadata like the title or associated session IDs.
 * Important implementation details:
 * 1.  **Client**: Uses `createAdminClient()` to bypass Row Level Security (RLS). This is appropriate for a server-side endpoint handling user edits, as it guarantees the update will succeed without RLS potentially blocking it, especially if the user's RLS context might be different from the story's creator.
 * 2.  **Partial Update**: Explicitly updates only the `sections` and `updated_at` fields, preserving all other fields of the story record.
 * 3.  **Error Handling**: Throws an `Error` if the update operation fails, signaling issues to the calling process.
 */
export async function updateStorySections(
  id: string,
  sections: StorySection[]
): Promise<void> {
  const supabase = createAdminClient()
  const { error } = await supabase
    .from('semester_stories')
    .update({ sections, updated_at: new Date().toISOString() })
    .eq('id', id)
  if (error) throw new Error(`Failed to update story sections: ${error.message}`)
}
