/**
 * @file lib/db/tierData.ts
 *
 * Per-session question quality tier classification data.
 *
 * Tier data is generated by `lib/ai/tierClassifier.ts` after each session
 * upload and stores two pieces of information:
 *  - `tier_counts`      — aggregate count per tier (Tier 1–4)
 *  - `tier_assignments` — per-question tier mapping keyed by question identifier
 *
 * Table: session_tier_data
 *
 * Called by:
 *   - app/api/sessions/[id]/route.ts    (GET — getTierData, embedded in session detail)
 *   - app/api/compare/route.ts          (GET — getTierDataBySessionIds for side-by-side)
 *   - lib/ai/tierClassifier.ts          (write path — upsertTierData after classification)
 */

import { createAdminClient, createClient } from '@/lib/supabase/server'
import type { TierData, SessionTierData, SessionTierDataRow } from '@/types'

/**
 * Map a raw `session_tier_data` row to the camelCase domain type.
 */
/**
 * Map a raw `session_tier_data` row to the camelCase domain type.
 *
 * It is used to transform data retrieved directly from the database into a more ergonomic and type-safe format for use within the application.
 *
 * This function ensures consistency in how `SessionTierData` objects are represented throughout the codebase by converting snake_case database column names (like `session_id`, `created_at`) to camelCase property names (`sessionId`, `createdAt`). This separation of concerns keeps the internal application logic clean and independent of the database's specific naming conventions.
 */
function rowToTierData(row: SessionTierDataRow): SessionTierData {
  return {
    id: row.id,
    sessionId: row.session_id,
    tierCounts: row.tier_counts,
    tierAssignments: row.tier_assignments,
    createdAt: row.created_at,
  }
}

/**
 * Insert or replace tier classification data for a session.
 *
 * Uses upsert on `session_id` so re-running the classifier (e.g. after a
 * prompt change) replaces the previous result without creating a duplicate row.
 *
 * @param sessionId - UUID of the session being classified
 * @param tierData  - `TierData` with `tierCounts` and `tierAssignments` from the AI agent
 * @throws {Error} If the upsert fails
 *
 * Client: createAdminClient() — bypasses RLS
 *         (tier classification runs as a fire-and-forget background job with no auth context)
 * Called by: lib/ai/tierClassifier.ts
 */
/**
 * Insert or replace tier classification data for a session.
 *
 * This function is used to store the results of the AI tier classification process. The use of `upsert` is crucial because tier classification can be re-run (e.g., after a prompt change); this ensures that re-classifying a session updates the existing data instead of creating a duplicate row, maintaining data integrity.
 *
 * It uses `createAdminClient()` to bypass Row Level Security (RLS) because tier classification often runs as a fire-and-forget background job without an authenticated user context. The `onConflict: 'session_id'` option in the upsert operation handles the replacement logic. Errors during the upsert operation are caught and re-thrown as a generic `Error`.
 */
export async function upsertTierData(sessionId: string, tierData: TierData): Promise<void> {
  const supabase = createAdminClient()
  const { error } = await supabase
    .from('session_tier_data')
    .upsert(
      {
        session_id: sessionId,
        tier_counts: tierData.tierCounts,
        tier_assignments: tierData.tierAssignments,
      },
      { onConflict: 'session_id' }
    )

  if (error) throw new Error(`Failed to upsert tier data: ${error.message}`)
}

/**
 * Retrieve tier classification data for a single session.
 * Returns `null` (without throwing) if no tier data exists yet or the query fails.
 *
 * @param sessionId - UUID of the session
 * @returns `SessionTierData` or `null`
 *
 * Client: createClient() — RLS enforced (professor can only read their own sessions' data)
 * Called by: app/api/sessions/[id]/route.ts (GET)
 */
/**
 * Retrieve tier classification data for a single session.
 *
 * This function is primarily used by API endpoints or UI components that need to display the tier classification details for a specific session. It provides a convenient way to access this data for individual session views.
 *
 * It utilizes `createClient()` which means Supabase's Row Level Security (RLS) is enforced, ensuring that only users with appropriate permissions (e.g., professors accessing their own sessions) can retrieve the data. The `.maybeSingle()` method is used to retrieve at most one row, and it gracefully returns `null` if no data is found for the given `sessionId` or if a database error occurs, rather than throwing an exception.
 */
export async function getTierData(sessionId: string): Promise<SessionTierData | null> {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('session_tier_data')
    .select('*')
    .eq('session_id', sessionId)
    .maybeSingle()

  if (error || !data) return null
  return rowToTierData(data as SessionTierDataRow)
}

/**
 * Retrieve tier classification data for multiple sessions in a single query.
 *
 * Used by the comparison view to display tier breakdowns side-by-side without
 * N individual round-trips.  Results are returned as a `Map` keyed by session ID
 * for O(1) lookup in the calling component.
 *
 * @param sessionIds - Array of session UUIDs to fetch (empty array returns empty Map)
 * @returns `Map<sessionId, SessionTierData>` — missing sessions are simply absent from the map
 *
 * Client: createAdminClient() — bypasses RLS
 *         (comparison view may aggregate data across sessions; admin client avoids
 *          partial result sets if a session belongs to a different RLS context)
 * Called by: app/api/compare/route.ts (GET)
 */
/**
 * Retrieve tier classification data for multiple sessions in a single query.
 *
 * This function is specifically designed for scenarios like a comparison view, where data for several sessions needs to be displayed side-by-side. It significantly improves performance by fetching all necessary data with a single database round-trip, avoiding the N+1 problem that would arise from making individual calls to `getTierData` for each session.
 *
 * It uses `createAdminClient()` to bypass RLS. This is important for the comparison view, which might aggregate data across sessions that could potentially belong to different RLS contexts. Bypassing RLS ensures that a complete result set is always returned, regardless of individual session ownership. The function includes a guard clause to prevent querying the database with an empty array of `sessionIds`, returning an empty `Map` immediately. Results are transformed into a `Map` keyed by `sessionId` for efficient O(1) lookup in the calling component.
 */
export async function getTierDataBySessionIds(
  sessionIds: string[]
): Promise<Map<string, SessionTierData>> {
  // Guard: skip the query entirely for an empty input to avoid a DB error
  if (sessionIds.length === 0) return new Map()

  const supabase = createAdminClient()
  const { data, error } = await supabase
    .from('session_tier_data')
    .select('*')
    .in('session_id', sessionIds)

  if (error || !data) return new Map()

  // Build a Map for O(1) lookup in the caller
  const map = new Map<string, SessionTierData>()
  for (const row of data) {
    const td = rowToTierData(row as SessionTierDataRow)
    map.set(td.sessionId, td)
  }
  return map
}
