/**
 * @file OutputPreview.tsx
 * Structured display of the AI-generated interview sheet output.
 *
 * Rendered by: app/(app)/preview/page.tsx (questions tab)
 * Calls: parseSections() from lib/parse/parseQuestions — parses the raw Grok
 *   markdown into a structured array of sections (title, primary question, backup question).
 *
 * Data flow: the parent page reads the raw output string from sessionStorage
 * (keyed as `session_${sessionId}`) to avoid a redundant API round-trip when
 * navigating between tabs. This component receives that string as `output` and
 * delegates all parsing to parseSections().
 */

import { parseSections } from '@/lib/parse/parseQuestions'

/**
 * Renders a single question row (primary or backup) within a section card.
 * Attribution is shown in muted italics after the question text.
 */
/**
 * What it does: Renders a single question row, displaying its label (e.g., 'Primary', 'Backup'), the question text itself, and the student attribution.
 * Why it is used: This component provides a consistent visual format for presenting individual questions (both primary and backup) within the larger interview section cards. It encapsulates the specific styling for a question line, promoting reusability and maintainability.
 * Important implementation details:
 * - It accepts a `q` prop with `label`, `text`, and `attribution` string properties.
 * - Styling is applied using Tailwind CSS classes, utilizing custom CSS variables for font families (`--font-dm-sans`) and colors (`--text-primary`, `--text-secondary`, `--text-muted`).
 * - The question's label is rendered in a bold font, the question text is normal, and the attribution is displayed in muted, italicized text.
 */
function QuestionRow({ q }: { q: { label: string; text: string; attribution: string } }) {
  return (
    <p className="leading-relaxed mb-2 text-sm font-[family-name:var(--font-dm-sans)] text-[var(--text-secondary)]">
      <span className="font-semibold text-[var(--text-primary)]">{q.label}:</span>{' '}
      {q.text}{' '}
      <span className="text-[var(--text-muted)] italic">({q.attribution})</span>
    </p>
  )
}

/**
 * Renders the full 10-section interview sheet as a scrollable card list.
 *
 * @param output - Raw markdown string from the Grok AI; parsed by `parseSections()`.
 *
 * Each section card shows:
 * - A section number label
 * - A theme title (orange left-border accent)
 * - The primary question with its student attribution
 * - An optional backup question with attribution
 *
 * Uses: `parseSections()` from lib/parse/parseQuestions
 */
/**
 * What it does: Renders the complete 10-section interview sheet as a scrollable list of cards. It takes raw markdown output from an AI, parses it into structured data, and then displays each section with its theme, primary question, and an optional backup question.
 * Why it is used: This component is crucial for visualizing the generated AI interview questions in a structured and user-friendly format. It allows users to review the output from the AI in an organized manner, making the generated content easy to digest.
 * Important implementation details:
 * - It receives a single `output` prop, which is expected to be a raw markdown string generated by the Grok AI.
 * - It critically depends on the `parseSections` utility from `@/lib/parse/parseQuestions` to transform the raw markdown string into a structured array of section objects, each containing titles and question details.
 * - It iterates over the `sections` array, rendering each section within its own `div` element.
 * - Each section card displays a section number, a theme title (visually accented with an orange left border), and uses the `QuestionRow` component to render the primary and optionally the backup questions.
 * - Styling is extensively handled by Tailwind CSS classes, including the use of CSS variables for theming (`--surface`, `--surface-elevated`, `--border-accent`, `--text-primary`, `--text-muted`) to ensure visual consistency.
 * - The component includes a header "Top Student Questions" and applies hover effects to individual section cards for an improved user experience.
 */
export function OutputPreview({ output }: { output: string }) {
  // parseSections transforms the raw AI markdown into structured section objects
  const sections = parseSections(output)

  return (
    <div className="rounded-2xl border border-[var(--border-accent)] overflow-hidden" style={{ background: 'var(--surface)' }}>
      <div className="px-6 py-4 border-b border-[var(--border-accent)]" style={{ background: 'var(--surface-elevated)' }}>
        <p className="text-xs text-[var(--text-muted)] font-semibold uppercase tracking-widest font-[family-name:var(--font-dm-sans)]">
          Top Student Questions
        </p>
      </div>
      <div className="flex flex-col gap-0">
        {sections.map((section, i) => (
          <div
            key={i}
            className="p-6 border-b border-[var(--border-accent)] last:border-b-0 hover:bg-[var(--surface-elevated)] transition-colors duration-150"
          >
            <p className="text-xs text-[var(--text-muted)] font-[family-name:var(--font-dm-sans)] uppercase tracking-widest mb-1">
              Section {i + 1}
            </p>
            <p className="font-[family-name:var(--font-playfair)] text-lg font-semibold text-[var(--text-primary)] mb-3 border-l-2 border-[#f36f21] pl-3">
              {section.title}
            </p>
            {section.primary && <QuestionRow q={section.primary} />}
            {section.backup && <QuestionRow q={section.backup} />}
          </div>
        ))}
      </div>
    </div>
  )
}
