import { NextResponse } from 'next/server'
import { getCurrentUser } from '@/lib/db/users'
import { getSemesterComparisonData } from '@/lib/db/semesterComparison'
import { generateCohortComparison } from '@/lib/ai/semesterComparison'

export const dynamic = 'force-dynamic'

/**
 * POST /api/semesters/compare
 *
 * Performs a cross-semester cohort comparison: fetches aggregated participation
 * and engagement metrics for the specified semesters, then generates an AI
 * narrative summarising the differences.
 *
 * @param request - JSON body:
 *   ```json
 *   { "semesterIds": ["uuid-a", "uuid-b", ...] }
 *   ```
 *   At least **2** semester IDs are required. IDs must belong to the authenticated
 *   professor (enforced inside `getSemesterComparisonData`).
 * @returns Spread of `SemesterComparisonData` plus an additional `aiNarrative`
 *   string field containing the Gemini-generated analysis. Shape includes:
 *   - `semesters` — per-semester summary objects (session counts, student counts,
 *     avg submissions, theme persistence)
 *   - `aiNarrative` — natural-language cohort comparison generated by Gemini
 * @remarks
 *   - **Auth**: Requires a valid session cookie. Returns 401 if unauthenticated.
 *   - Malformed JSON body returns 400 before auth is relevant.
 *   - Fewer than 2 `semesterIds` returns 400.
 *   - The AI call (`generateCohortComparison`) uses Gemini via `geminiClient.ts`
 *     and may take several seconds for large cohorts.
 *   - Results are not cached — each call re-queries the DB and re-runs Gemini.
 *     The comparison data is stored in the `cohort_comparisons` table for
 *     historical reference by `getSemesterComparisonData`.
 * @see {@link lib/db/semesterComparison.ts} — `getSemesterComparisonData()`
 * @see {@link lib/ai/semesterComparison.ts} — `generateCohortComparison()`
 */
export async function POST(request: Request) {
  const user = await getCurrentUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: { semesterIds?: string[] }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { semesterIds } = body
  if (!Array.isArray(semesterIds) || semesterIds.length < 2) {
    return NextResponse.json(
      { error: 'At least 2 semester IDs are required' },
      { status: 400 }
    )
  }

  try {
    // Fetch aggregated cohort metrics for all selected semesters
    const data = await getSemesterComparisonData(user.id, semesterIds)
    // Generate the Gemini AI narrative from the structured comparison data
    const aiNarrative = await generateCohortComparison(data)

    return NextResponse.json({ ...data, aiNarrative })
  } catch (err) {
    console.error('[/api/semesters/compare] Error:', err)
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Comparison failed' },
      { status: 500 }
    )
  }
}
