/**
 * @file types/debrief.ts
 * @description Post-session professor debrief types.
 *
 * After each speaker session the professor can fill out a structured debrief
 * (the "debrief" tab on /preview). It captures ratings, per-question feedback,
 * surprise moments, speaker impressions, and student observations. When marked
 * complete, an AI summary is generated by `lib/ai/debriefSummary.ts`.
 *
 * Data is stored in the `session_debriefs` table and accessed through:
 *   GET/POST /api/sessions/[id]/debrief
 *   POST     /api/sessions/[id]/debrief/complete
 *
 * Row vs Domain:
 *   SessionDebriefRow — raw Supabase row shape (snake_case)
 *   SessionDebrief    — camelCase domain object used in UI components
 *
 * Related components: DebriefPanel, DownloadButtons (includes debrief in exports)
 */

/**
 * How an individual question performed when asked during the session.
 * Mirrors the professor's post-session assessment per question.
 */
/**
 * What it does
 * Defines a union type representing the possible performance statuses for a question asked during a session.
 * Why it is used
 * To categorize and record how effectively a particular interview question was received or performed during a live session. This helps professors evaluate the quality and impact of their questions.
 * Important implementation details
 * It is a union type consisting of four string literals: 'home_run' (excellent), 'solid' (good), 'flat' (poor), and 'unused' (not asked).
 */
export type QuestionStatus = 'home_run' | 'solid' | 'flat' | 'unused'

/**
 * Lifecycle state of a debrief record.
 * 'draft' means the professor is still filling it in; 'complete' triggers
 * AI summary generation and locks certain fields.
 */
/**
 * What it does
 * Defines the lifecycle state of a debrief record.
 * Why it is used
 * To manage the workflow and progression of a session debrief. It distinguishes between a debrief being actively edited by a professor ('draft') and one that has been finalized ('complete'), which triggers automated processes.
 * Important implementation details
 * It is a union type with two string literals: 'draft' and 'complete'. The transition to 'complete' is a critical event, as it triggers AI summary generation and typically locks certain fields from further modification, marking the debrief as final.
 */
export type DebriefStatus = 'draft' | 'complete'

/**
 * Per-question post-session feedback entry.
 * Stored as a JSONB array in `session_debriefs.questions_feedback`.
 */
/**
 * What it does
 * Represents a detailed feedback entry for a single question asked during an interview session.
 * Why it is used
 * To store granular, structured feedback about each question's performance, attribution, and context within a session debrief. This allows professors to analyze the effectiveness and reception of individual questions.
 * Important implementation details
 * This interface includes fields for the full question text, student attribution, the theme section it belonged to, its role (primary or backup), and its performance status using the `QuestionStatus` type. It is designed to be stored as a JSONB array within the `session_debriefs.questions_feedback` column in the database.
 */
export interface QuestionFeedback {
  /** The full text of the question as it appeared in the interview sheet. */
  questionText: string
  /** Student name(s) attributed to this question. */
  attribution: string
  /** The theme section this question belonged to. */
  themeTitle: string
  /** Whether this was the primary question for the theme or a backup. */
  role: 'primary' | 'backup'
  /** How well the question performed when asked in the actual session. */
  status: QuestionStatus
}

/**
 * A professor's note about a specific student observed during the session.
 * Stored as a JSONB array in `session_debriefs.student_observations`.
 */
/**
 * What it does
 * Represents a specific note or observation made by a professor about an individual student during an interview session.
 * Why it is used
 * To capture student-specific feedback, behavioral notes, or notable moments that might not fit into general session or question feedback. This allows for targeted observations on individual participants.
 * Important implementation details
 * This interface contains `studentName` to identify the student and `note` for the observation text. It is designed to be stored as a JSONB array within the `session_debriefs.student_observations` column in the database, allowing for multiple observations per debrief.
 */
export interface StudentObservation {
  studentName: string
  note: string
}

/** Raw database row for the `session_debriefs` table. */
/**
 * What it does
 * Defines the exact structure of a raw database row as stored in the `session_debriefs` table.
 * Why it is used
 * To accurately represent the data directly from the PostgreSQL database, including `snake_case` naming conventions and all database-managed fields. This type is essential for direct database interactions, ORM mappings, and SQL query results.
 * Important implementation details
 * All fields use `snake_case` naming. It includes unique identifiers (`id`, `session_id`, `user_id`) and various free-text fields. Complex data, such as `questions_feedback` and `student_observations`, are stored as JSONB arrays. Fields like `overall_rating` and `ai_summary` are nullable, indicating they might not be present initially or until a certain debrief status is reached. `created_at` and `updated_at` are standard database timestamps.
 */
export interface SessionDebriefRow {
  id: string
  session_id: string
  user_id: string
  /** 1–5 star overall rating of the session; null until set by the professor. */
  overall_rating: number | null
  /** Per-question performance feedback JSONB array. */
  questions_feedback: QuestionFeedback[]
  /** Free-text: unexpected moments or off-script topics that landed well. */
  surprise_moments: string
  /** Free-text: professor's overall impression of the speaker. */
  speaker_feedback: string
  /** Per-student observations JSONB array. */
  student_observations: StudentObservation[]
  /** Free-text: topics the professor wants to follow up on in future sessions. */
  followup_topics: string
  /** Free-text: private notes not included in any exports or AI analysis. */
  private_notes: string
  /** AI-generated summary produced when status transitions to 'complete'. */
  ai_summary: string | null
  status: DebriefStatus
  created_at: string
  updated_at: string
}

/**
 * Domain-level session debrief object (camelCase).
 * Returned by `getDebrief()` and used in the DebriefPanel component.
 */
/**
 * What it does
 * Defines the domain-level representation of a session debrief object, formatted with `camelCase` for use within the application's business logic and user interface.
 * Why it is used
 * To provide a clean, developer-friendly representation of the debrief data, abstracting away the database's `snake_case` for easier consumption by frontend applications (e.g., React components) and application services. It's typically the result of a data transformation from `SessionDebriefRow`.
 * Important implementation details
 * All field names are in `camelCase`, corresponding to the `SessionDebriefRow` but adapted for common application patterns. It includes all the same data points as `SessionDebriefRow`, but with names adjusted for consistency within the application domain. This type is commonly used when fetching and displaying debrief data to users.
 */
export interface SessionDebrief {
  id: string
  sessionId: string
  userId: string
  /** 1–5 star overall rating of the session; null until set by the professor. */
  overallRating: number | null
  /** Per-question performance feedback. */
  questionsFeedback: QuestionFeedback[]
  /** Free-text: unexpected moments or off-script topics that landed well. */
  surpriseMoments: string
  /** Free-text: professor's overall impression of the speaker. */
  speakerFeedback: string
  /** Per-student observations. */
  studentObservations: StudentObservation[]
  /** Free-text: topics the professor wants to follow up on in future sessions. */
  followupTopics: string
  /** Free-text: private notes not included in any exports or AI analysis. */
  privateNotes: string
  /** AI-generated summary; null until the debrief is marked complete. */
  aiSummary: string | null
  status: DebriefStatus
  createdAt: string
  updatedAt: string
}

/**
 * Input shape for `upsertDebrief()` in lib/db/debriefs.ts.
 * All fields except sessionId/userId are optional to support auto-save
 * (each field can be updated independently as the professor types).
 */
/**
 * What it does
 * Defines the input shape for the `upsertDebrief()` function (e.g., in `lib/db/debriefs.ts`), used for creating or updating a session debrief record.
 * Why it is used
 * To enable flexible partial updates and auto-save functionality. By making most fields optional, the system can update individual debrief fields independently as a professor types or makes changes, without requiring all fields to be present in every request.
 * Important implementation details
 * `sessionId` and `userId` are required to identify the specific debrief being updated or inserted. All other fields are optional (`?`), allowing for targeted updates where only the changed values are provided. The `DebriefStatus` field is also optional, enabling status transitions to be managed as part of the upsert operation.
 */
export interface UpsertDebriefInput {
  sessionId: string
  userId: string
  overallRating?: number | null
  questionsFeedback?: QuestionFeedback[]
  surpriseMoments?: string
  speakerFeedback?: string
  studentObservations?: StudentObservation[]
  followupTopics?: string
  privateNotes?: string
  status?: DebriefStatus
}
