/**
 * @file types/insights.ts
 * @description Class-level insight types produced by the Gemini insights agent.
 *
 * These types represent cross-session analysis generated by
 * `lib/ai/classInsights.ts` (`generateClassInsights()`), which runs
 * fire-and-forget after each session upload and debrief completion.
 *
 * Results are stored in the `class_insights` table (one row per professor,
 * upserted on each regeneration) and exposed through:
 *   GET /api/analytics/insights
 *
 * Also includes speaker recommendation types, which are generated by
 * `lib/ai/speakerRecommendations.ts` and exposed through:
 *   GET /api/analytics/recommendations
 *
 * All types here are Domain types (no DB Row equivalent — the JSONB is stored
 * and returned as-is).
 */

/**
 * A single data point in the semester-long theme evolution timeline.
 * Used to build the sparkline/timeline in the ClassInsights panel.
 */
/**
 * Represents a single entry detailing the evolution of themes for a specific session.
 *
 * What it does: This interface structures data about a single class session, including its ID, the speaker's name, the date, and a list of themes identified from that session's AI output.
 * Why it is used: It is crucial for tracking and visualizing how themes emerge, evolve, and persist across multiple class sessions over time, particularly for rendering the theme evolution timeline on the analytics page.
 * Important implementation details: It includes `sessionId` to identify the unique session, `speakerName` for display, `date` as an ISO string for chronological ordering, and an array of `themes` as strings.
 */
export interface ThemeEvolutionEntry {
  sessionId: string
  speakerName: string
  /** ISO date string of the session. */
  date: string
  /** Theme titles extracted from the session's AI output. */
  themes: string[]
}

/**
 * Full class-level insights object stored in `class_insights.content` and
 * returned by GET /api/analytics/insights.
 *
 * Rendered in the /analytics page insights panel and (partially) embedded
 * in semester reports.
 */
/**
 * Full class-level insights object stored in `class_insights.content` and
 * returned by GET /api/analytics/insights.
 *
 * Rendered in the /analytics page insights panel and (partially) embedded
 * in semester reports.
 *
 * What it does: This interface defines the comprehensive structure for all class-level analytical insights generated by the system.
 * Why it is used: It serves as the primary data model for presenting a holistic view of class performance, engagement patterns, and actionable recommendations to professors on the analytics dashboard and in semester reports.
 * Important implementation details: It aggregates various insights like a `narrative` summary, `qualityTrend`, `topThemes`, `watchlist` for flagged students, `themeEvolution` data, optional `sessionEffectiveness` scores (dependent on debrief data), optional `speakerRecommendations` (dependent on sufficient data), and a `generatedAt` timestamp for freshness.
 */
export interface ClassInsights {
  /** Gemini-generated narrative paragraph summarising class-wide patterns. */
  narrative: string
  /** Overall trajectory of question quality across sessions. */
  qualityTrend: {
    direction: 'improving' | 'declining' | 'stable'
    description: string
  }
  /** Most recurring themes across all sessions with context and sample questions. */
  topThemes: Array<{
    title: string
    /** How many sessions this theme appeared in. */
    sessionCount: number
    /** True if this theme first appeared in the most recent session. */
    isNew: boolean
    summary: string
    /** Speaker names (not IDs) for the sessions where this theme appeared. */
    sessions: string[]
    sampleQuestions: string[]
  }>
  /**
   * Students flagged for professor attention — e.g. consistently surface-level
   * questions, sudden drop in quality, or unusual patterns.
   */
  watchlist: Array<{
    studentName: string
    reason: string
  }>
  /** Session-by-session theme data used to render the evolution timeline. */
  themeEvolution: ThemeEvolutionEntry[]
  /**
   * Optional per-session effectiveness scores derived from debrief ratings
   * and question tier data. Only present when sufficient debrief data exists.
   */
  sessionEffectiveness?: Array<{
    speakerName: string
    /** Professor's 1–5 star rating from the session debrief. */
    rating: number
    /** Count of Tier-1 ("home run") questions in this session. */
    homeRunCount: number
    /** Count of Tier-4 ("flat") questions in this session. */
    flatCount: number
  }>
  /** AI-generated speaker recommendations; present when enough data exists. */
  speakerRecommendations?: SpeakerRecommendations
  /** ISO timestamp of the last regeneration. */
  generatedAt: string
}

/**
 * Pattern analysis derived from past speaker debrief data.
 * Describes what types of speakers and topics have resonated most with the class.
 */
/**
 * Pattern analysis derived from past speaker debrief data.
 * Describes what types of speakers and topics have resonated most with the class.
 *
 * What it does: This interface defines the structure for AI-generated analysis of historical speaker debrief data, identifying patterns related to class engagement and question quality.
 * Why it is used: It provides professors with data-driven insights into which types of speakers, topics, and session formats have historically been most or least effective, helping them make informed decisions for future speaker invitations.
 * Important implementation details: It includes `bestEngagementTypes`, `topResonatingTopics` (with `avgRating` and `homeRunPct`), `successPatterns`, `cautionPatterns`, a `dataConfidence` level (low, moderate, high) indicating the reliability of the analysis, and an optional `insufficientDataNote`.
 */
export interface SpeakerPatternAnalysis {
  /** Description of engagement contexts where the class responds best. */
  bestEngagementTypes: string
  /** Topics that historically produced high question quality (high avg rating, high home-run %). */
  topResonatingTopics: Array<{
    topic: string
    /** Average professor debrief rating (1–5) for sessions on this topic. */
    avgRating: number
    /** Percentage of questions that were Tier-1 ("home run") for this topic. */
    homeRunPct: number
  }>
  /** Patterns correlated with successful, high-engagement sessions. */
  successPatterns: string[]
  /** Patterns or speaker types that have historically under-performed. */
  cautionPatterns: string[]
  /**
   * How much data backs this analysis.
   * 'low' means fewer than 3 sessions with debrief data.
   */
  dataConfidence: 'low' | 'moderate' | 'high'
  /** Explanatory note shown when dataConfidence is 'low' or 'moderate'. */
  insufficientDataNote: string | null
}

/**
 * AI-generated speaker recommendations for the professor's next semester.
 * Returned by GET /api/analytics/recommendations and embedded in `ClassInsights`.
 */
/**
 * AI-generated speaker recommendations for the professor's next semester.
 * Returned by GET /api/analytics/recommendations and embedded in `ClassInsights`.
 *
 * What it does: This interface defines the structure for AI-generated recommendations for future speakers, tailored to the class's historical engagement and learning patterns.
 * Why it is used: It assists professors in planning their curriculum for upcoming semesters by suggesting relevant topic areas, explaining the rationale, and outlining ideal speaker profiles based on past class performance and interests.
 * Important implementation details: It contains an array of specific `recommendations`, each detailing a `topicArea`, `whyRecommended`, `studentInterestSignals`, `complementsContrasts` with prior speakers, and an `idealSpeakerProfile`. It also embeds a `patternAnalysis` (of type `SpeakerPatternAnalysis`) and includes a `generatedAt` timestamp.
 */
export interface SpeakerRecommendations {
  recommendations: Array<{
    /** Broad topic area the recommended speaker should cover. */
    topicArea: string
    /** Why this topic area was recommended based on class history. */
    whyRecommended: string
    /** Student question patterns that signal interest in this area. */
    studentInterestSignals: string[]
    /** How this topic area complements or contrasts prior speakers. */
    complementsContrasts: string
    /** Description of the ideal speaker background for this recommendation. */
    idealSpeakerProfile: string
  }>
  patternAnalysis: SpeakerPatternAnalysis
  /** ISO timestamp of when these recommendations were generated. */
  generatedAt: string
}
