/**
 * @file types/semester.ts
 * @description Semester grouping types for organising sessions.
 *
 * Semesters are optional containers that group sessions together for reporting
 * and comparison. A professor can have at most one 'active' semester at a time;
 * all others are 'archived'. Sessions with `semester_id = NULL` are unassigned.
 *
 * Data is stored in the `semesters` table and accessed through:
 *   GET   /api/semesters           → SemesterSummary[] (with session counts)
 *   POST  /api/semesters           → creates a semester
 *   PATCH /api/semesters/[id]      → updates name, dates, or status
 *   POST  /api/semesters/assign    → bulk-assigns sessions to a semester
 *
 * Rendered on the /semesters management page.
 *
 * Row vs Domain:
 *   SemesterRow — raw Supabase row shape (snake_case, mirrors `semesters` table)
 *   Semester    — camelCase domain object used in the app
 */

/** Raw database row for the `semesters` table. */
/**
 * What it does: Defines the structure of a semester record as it is stored directly in the database.
 * Why it is used: This interface represents the raw data fetched from or stored into the database for semesters, serving as a direct mapping to a database table row.
 * Important implementation details: Field names use `snake_case` (e.g., `user_id`, `created_at`), which is a common convention for database columns. It includes `user_id` to link a semester to its owner, `created_at` for timestamping, and `status` to denote its active or archived state. `start_date` and `end_date` are expected to be ISO date strings (YYYY-MM-DD).
 */
export interface SemesterRow {
  id: string
  user_id: string
  name: string
  /** ISO date string for the start of the semester (YYYY-MM-DD). */
  start_date: string
  /** ISO date string for the end of the semester (YYYY-MM-DD). */
  end_date: string
  /** Only one semester per professor can be 'active' at a time. */
  status: 'active' | 'archived'
  created_at: string
}

/**
 * Domain-level semester object (camelCase).
 * Returned by `getSemesterById()` and used in the semesters page.
 */
/**
 * What it does: Represents the domain-level object for a semester, designed for use within the application's business logic and UI.
 * Why it is used: Provides a clean, application-friendly representation of a semester, typically transformed from `SemesterRow` (database representation) for consumption by frontend components or other backend services. It is explicitly returned by `getSemesterById()` functions and utilized on the semesters page to display and manage semester information.
 * Important implementation details: Field names use `camelCase` (e.g., `userId`, `startDate`), adhering to common JavaScript/TypeScript conventions. It includes core semester attributes like `id`, `userId`, `name`, `startDate`, `endDate`, `status`, and `createdAt`.
 */
export interface Semester {
  id: string
  userId: string
  name: string
  /** ISO date string for the start of the semester (YYYY-MM-DD). */
  startDate: string
  /** ISO date string for the end of the semester (YYYY-MM-DD). */
  endDate: string
  /** Only one semester per professor can be 'active' at a time. */
  status: 'active' | 'archived'
  createdAt: string
}

/**
 * Input shape for creating a new semester via `insertSemester()`.
 * Called from POST /api/semesters.
 */
/**
 * What it does: Defines the required data shape for creating a brand new semester.
 * Why it is used: This interface specifies the expected payload for API requests (e.g., `POST /api/semesters`) that aim to add a new semester. It ensures that all necessary information is provided by the client when creating a semester, facilitating valid data entry and processing by the `insertSemester()` function.
 * Important implementation details: It deliberately excludes fields such as `id`, `status`, and `createdAt` because these are typically generated by the backend or database upon the semester's creation. The focus is solely on the data that the user provides: `userId`, `name`, `startDate`, and `endDate` (all as ISO date strings).
 */
export interface CreateSemesterInput {
  userId: string
  name: string
  /** ISO date string (YYYY-MM-DD). */
  startDate: string
  /** ISO date string (YYYY-MM-DD). */
  endDate: string
}

/**
 * Input shape for updating an existing semester via `updateSemester()`.
 * All fields are optional — only provided fields are updated.
 * Used by PATCH /api/semesters/[id].
 */
/**
 * What it does: Defines the optional data shape for modifying an existing semester.
 * Why it is used: This interface allows for partial updates to a semester record. By making all fields optional, clients can send only the specific fields they wish to change, rather than having to provide the entire semester object. It is used by the `updateSemester()` function and typically consumed by `PATCH /api/semesters/[id]` API endpoints.
 * Important implementation details: All fields are marked as optional (`?`). A significant detail for the `status` field is that changing a semester's status to 'active' or 'archived' includes specific logic: if changing to 'active', it ensures only one semester for a given professor is active at a time by archiving any other currently active semesters. If changing to 'archived', it simply archives the specified semester.
 */
export interface UpdateSemesterInput {
  name?: string
  startDate?: string
  endDate?: string
  /** Changing status to 'archived' will set any other active semester to 'archived' first. */
  status?: 'active' | 'archived'
}

/**
 * Lightweight semester summary used in the /semesters list view.
 * Includes a derived session count and an optional link to a generated story.
 */
/**
 * What it does: Defines a lightweight summary object for a semester, optimized for display in lists or overviews.
 * Why it is used: This interface provides a concise set of information tailored for presentation in list views (e.g., on the `/semesters` page) or dashboards. It reduces the data payload compared to a full `Semester` object when only summary details are required, improving performance for displaying multiple semesters.
 * Important implementation details: Includes essential display information such as `id`, `name`, `status`, `startDate`, and `endDate`. It also incorporates derived data like `sessionCount` (the number of sessions associated with the semester) and an optional `storyId` (for linking to a generated narrative story, if one exists), enhancing the utility of the summary view.
 */
export interface SemesterSummary {
  id: string
  name: string
  status: 'active' | 'archived'
  /** Number of sessions assigned to this semester. */
  sessionCount: number
  startDate: string
  endDate: string
  /**
   * ID of the narrative story generated for this semester, if one exists.
   * Links to /stories/[storyId] from the semester card.
   */
  storyId?: string | null
}
