/**
 * @file types/session_synthesis.ts
 * @description Session synthesis types — cross-data-type intelligence for a single session.
 *
 * A session synthesis combines all three student submission types (question
 * submissions, debrief reflections, and speaker analyses) with the AI-generated
 * session analysis to produce a unified narrative about what happened before,
 * during, and after the speaker visit.
 *
 * Generated by `lib/ai/synthesisAgent.ts` and stored in the `session_syntheses` table.
 * Accessed through:
 *   GET/POST /api/sessions/[id]/synthesis → fetch or generate synthesis
 *
 * Domain type only — the synthesis is stored as a JSONB blob and returned as-is.
 * No separate DB Row type.
 */

// ── Session synthesis (cross-data-type intelligence) types ───────────────────

/**
 * Full synthesis of all data dimensions for a single session.
 * Returned by GET /api/sessions/[id]/synthesis and rendered in the synthesis
 * panel on the /preview page.
 */
export interface SessionSynthesis {
  narrative: string

  curiosity_resolution: Array<{
    question_theme: string
    addressed: boolean
    evidence: string
  }>

  theme_evolution: Array<{
    theme: string
    pre_session: string | null
    post_session: string | null
    evolution: string
  }>

  emergent_themes: Array<{
    theme: string
    source: 'debriefs' | 'speaker_analyses'
    description: string
    student_count: number
  }>

  tone_shift: {
    pre: { dominant: string; description: string }
    post: { dominant: string; description: string }
    shift_narrative: string
  }

  gaps: Array<{
    theme: string
    present_in: string[]
    absent_from: string[]
    significance: string
  }>

  data_completeness: {
    has_questions: boolean
    has_debriefs: boolean
    has_speaker_analyses: boolean
    missing_note: string | null
  }
}
