/**
 * @file types/speaker_portal.ts
 * @description Speaker portal types — the public-facing portal given to guest speakers.
 *
 * The speaker portal is a richer, token-protected public page that gives the
 * speaker context before their visit and collects feedback afterwards. It has
 * two distinct phases:
 *   1. Pre-session  — portal content generated by `lib/ai/speakerPortal.ts`
 *   2. Post-session — feedback captured via `PostSessionFeedback`, generated
 *                     by `lib/ai/speakerPortalPostSession.ts`
 *
 * Portals are accessed through:
 *   GET/POST /api/sessions/[id]/portal         → fetch or generate portal content
 *   POST     /api/sessions/[id]/portal/publish → publish portal (sets is_published + share_token)
 *   GET      /api/speaker/[token]              → public portal fetch (no auth required)
 *
 * Rendered on /preview/portal (professor preview) and the public /speaker/[token] page.
 *
 * Row vs Domain:
 *   SpeakerPortalRow — raw Supabase row (snake_case, `speaker_portals` table)
 *   SpeakerPortal    — camelCase domain object used in the app
 *
 * Note: like briefs, `editedContent` stores professor overrides to the AI content.
 */

/**
 * The structured content of the speaker portal's pre-session view.
 * Stored as JSONB in `speaker_portals.content`.
 */
/**
 * What it does
 * Defines the comprehensive structure for the AI-generated pre-session content displayed to a speaker in their personalized portal.
 * Why it is used
 * It standardizes the data format for all information presented to a speaker before their session, including personalized greetings, insights into student interests, sample questions, suggested talking points, an audience profile, and insights from past sessions. This ensures consistency, proper rendering, and type safety across the speaker portal UI.
 * Important implementation details
 * This is a complex, deeply nested object that reflects various distinct sections of the speaker portal UI. Fields like `welcome`, `studentInterests`, `sampleQuestions`, `talkingPoints`, `audienceProfile`, and `pastSpeakerInsights` each correspond to a specific component or information block. The `sentiment` values are percentages (0-100) and should ideally sum to approximately 100. The `pastSpeakerInsights.available` flag indicates the presence or absence of prior debrief data.
 */
export interface SpeakerPortalContent {
  /** Welcome section personalising the portal for the speaker. */
  welcome: {
    speakerName: string
    professorName: string
    /** Course name or label. */
    courseLabel: string
    sessionDate: string
    /** Number of students in the class. */
    studentCount: number
    /** AI-generated personalised greeting message for the speaker. */
    greeting: string
  }
  /** Overview of what the class cares about and wants to explore. */
  studentInterests: {
    /** Narrative paragraph describing the class's interests and motivations. */
    narrative: string
    topThemes: Array<{
      title: string
      description: string
    }>
  }
  /** Representative student questions the speaker can expect. */
  sampleQuestions: {
    /** Context-setting narrative about the type and quality of questions. */
    narrative: string
    questions: Array<{
      /** The theme this question belongs to. */
      theme: string
      question: string
    }>
  }
  /** Suggested talking points and why each would resonate with this class. */
  talkingPoints: Array<{
    point: string
    rationale: string
  }>
  /** Data-driven profile of the class's engagement style and sentiment. */
  audienceProfile: {
    narrative: string
    /**
     * Emotional/motivational tone distribution across student questions.
     * Values are percentages (0–100) that should sum to ~100.
     */
    sentiment: {
      aspirational: number
      curious: number
      personal: number
      critical: number
    }
    /** Topics the class repeatedly returns to across multiple sessions. */
    recurringInterests: string[]
  }
  /**
   * Insights derived from past speaker sessions (ratings, patterns, notable moments).
   * `available` is false when no prior debrief data exists.
   */
  pastSpeakerInsights: {
    available: boolean
    narrative: string
    highlights: Array<{
      insight: string
      context: string
    }>
  }
}

/**
 * Post-session feedback collected from or about the speaker after their visit.
 * Generated by `lib/ai/speakerPortalPostSession.ts` based on professor debrief data.
 * Stored as JSONB in `speaker_portals.post_session`.
 */
/**
 * What it does
 * Defines the structure for feedback and insights collected from or about a speaker after their visit.
 * Why it is used
 * It is used to store and display post-session information, including the speaker's rating, topics that resonated, individual student highlights, professor's notes, and an AI-generated narrative summary. This data provides a valuable debrief, a record of the speaker's engagement, and can inform future sessions and improvements.
 * Important implementation details
 * This object is typically generated by specific AI services, such as `lib/ai/speakerPortalPostSession.ts`, which synthesizes feedback from various sources (e.g., professor debriefs). It is stored as a JSONB column in the `speaker_portals.post_session` field within the database. The `overallRating` is expected to be an integer between 1 and 5.
 */
export interface PostSessionFeedback {
  /** The speaker's overall rating of the session (1–5). */
  overallRating: number
  /** Topics the speaker felt resonated most with the class. */
  topicsResonated: string[]
  /** Noteworthy observations about individual student engagement. */
  studentHighlights: string
  /** Professor-authored notes captured in the post-session debrief. */
  professorNotes: string
  /** AI-generated narrative synthesising the post-session feedback. */
  narrative: string
}

/** Raw database row for the `speaker_portals` table. */
/**
 * What it does
 * Represents the raw data structure of a single row in the `speaker_portals` database table.
 * Why it is used
 * This interface defines the schema for direct database interactions, ensuring data integrity and consistency when reading from or writing to the `speaker_portals` table. It serves as the canonical "storage" representation of a speaker portal record.
 * Important implementation details
 * Column names typically follow a snake_case convention, which is common for database schemas. The `content`, `edited_content`, and `post_session` fields are designed to store JSONB data, holding `SpeakerPortalContent` and `PostSessionFeedback` objects respectively. `edited_content` and `post_session` can be `null` under specific conditions (e.g., no edits made, or post-session phase not triggered). The `share_token` is an opaque identifier for public access, and `is_published` controls the visibility of the portal at its public URL.
 */
export interface SpeakerPortalRow {
  id: string
  session_id: string
  user_id: string
  /** JSONB — the AI-generated portal content (pre-session view). */
  content: SpeakerPortalContent
  /**
   * JSONB — professor's manual edits to the portal content.
   * Null if the professor has not edited since generation.
   */
  edited_content: SpeakerPortalContent | null
  /**
   * JSONB — post-session feedback; null until the post-session phase is triggered.
   */
  post_session: PostSessionFeedback | null
  /** Opaque token used in the public portal URL: /speaker/[token] */
  share_token: string
  /** Whether the portal has been published (made accessible at its public URL). */
  is_published: boolean
  created_at: string
  updated_at: string
}

/**
 * Domain-level speaker portal object (camelCase).
 * Returned by GET /api/sessions/[id]/portal and GET /api/speaker/[token].
 */
/**
 * What it does
 * Represents the domain-level (application-facing) speaker portal object, typically used in application logic and API responses.
 * Why it is used
 * It provides a consistent, camelCase representation of speaker portal data within the application layer, abstracting away database-specific naming conventions (`snake_case`). This format is optimized for consumption by frontend clients and internal application services, ensuring a clean and idiomatic interface.
 * Important implementation details
 * Properties use camelCase naming, aligning with standard JavaScript/TypeScript conventions. This interface is often derived from a `SpeakerPortalRow` object through a mapping or transformation layer. It is specifically designed to be returned by API endpoints, such as `GET /api/sessions/[id]/portal` and `GET /api/speaker/[token]`. The `editedContent` field is prioritized for display in public portal routes when it is non-null, indicating manual professor edits over the AI-generated `content`. The `postSession` field will be `null` until the post-session phase is explicitly triggered.
 */
export interface SpeakerPortal {
  id: string
  sessionId: string
  userId: string
  /** The AI-generated portal content (pre-session view). */
  content: SpeakerPortalContent
  /**
   * Professor's manual edits; null if unchanged since generation.
   * The public portal route serves this when non-null.
   */
  editedContent: SpeakerPortalContent | null
  /**
   * Post-session feedback object; null until the post-session phase is triggered.
   */
  postSession: PostSessionFeedback | null
  /** Opaque token used in the public portal URL: /speaker/[token] */
  shareToken: string
  /** Whether the portal is live at its public URL. */
  isPublished: boolean
  createdAt: string
  updatedAt: string
}
