/**
 * @file types/speaker_brief.ts
 * @description Speaker brief types — pre-session context packages for guest speakers.
 *
 * A speaker brief is a curated document sent to the guest speaker before they
 * visit the class. It summarises who the students are, what themes they care
 * about, and what questions they've prepared. Generated by `lib/ai/speakerBrief.ts`.
 *
 * Briefs are accessed through:
 *   GET/POST /api/sessions/[id]/brief          → fetch or generate the brief
 *   GET      /api/sessions/[id]/brief/download → export as PDF or plain text
 *
 * Rendered on /preview/brief (professor preview) and within the speaker portal
 * at /speaker/[token].
 *
 * Row vs Domain:
 *   SpeakerBriefRow — raw Supabase row (snake_case, `speaker_briefs` table)
 *   SpeakerBrief    — camelCase domain object used in the app
 *
 * Note: `editedContent` lets the professor override the AI-generated brief
 * before sending it. Exports use `editedContent` if present, otherwise `content`.
 */

/**
 * The structured content of a speaker brief document.
 * Stored as JSONB in `speaker_briefs.content` (and `edited_content` if the
 * professor has made manual edits).
 */
/**
 * Defines the structure for the rich, AI-generated content of a speaker brief. This interface encapsulates all the dynamic, textual information that forms the core of the brief presented to a speaker.
 *
 * It is used to standardize the data model for the speaker brief content, both for initial AI generation and subsequent professor edits. This ensures consistency in how brief information is structured and displayed across the application.
 *
 * This interface includes nested objects and arrays for various sections like `header` (metadata), `topThemes` (recurring student questions), and `talkingPoints` (suggested discussion topics). This detailed structure allows for a comprehensive and informative brief.
 */
export interface SpeakerBriefContent {
  /** Metadata shown in the brief header. */
  header: {
    speakerName: string
    /** Formatted date of the session. */
    date: string
    /** Number of students who submitted questions for this session. */
    studentCount: number
    /** Course name or label (e.g. "MGMT 485 — Leadership in Practice"). */
    courseLabel: string
  }
  /** AI-generated narrative introducing the class and their interests to the speaker. */
  narrative: string
  /** Top recurring themes in the student questions, with descriptions. */
  topThemes: Array<{
    title: string
    description: string
  }>
  /** Suggested talking points for the speaker, with rationale for each. */
  talkingPoints: Array<{
    point: string
    rationale: string
  }>
  /** Paragraph describing the class context (major, year, prior speakers, etc.). */
  classContext: string
  /** What the speaker should expect in terms of student engagement style and format. */
  whatToExpect: string
}

/** Raw database row for the `speaker_briefs` table. */
/**
 * Represents the direct database schema for a speaker brief record in the `speaker_briefs` table. This interface maps directly to the columns of the database table.
 *
 * It is used to facilitate type-safe database interactions, such as ORM queries, data fetching, and data insertion, ensuring that operations against the database table conform to a defined structure.
 *
 * Important implementation details:
 * - Property names use `snake_case` to match typical database column naming conventions.
 * - It contains a `content` property of type `SpeakerBriefContent` for the original AI-generated brief.
 * - It includes an `edited_content` property (also `SpeakerBriefContent` or `null`) which represents professor's manual edits. This separation allows the application to track changes and prioritize edited content for exports and display.
 * - Both `content` and `edited_content` are typically stored as `JSONB` in the database, enabling structured JSON data storage.
 */
export interface SpeakerBriefRow {
  id: string
  session_id: string
  user_id: string
  /** JSONB — the AI-generated brief content. */
  content: SpeakerBriefContent
  /**
   * JSONB — professor's manual edits to the brief.
   * Null if the professor has not edited the brief since generation.
   * Export routes prefer this over `content` when non-null.
   */
  edited_content: SpeakerBriefContent | null
  created_at: string
  updated_at: string
}

/**
 * Domain-level speaker brief object (camelCase).
 * Returned by GET /api/sessions/[id]/brief and used in the brief preview page.
 */
/**
 * Represents the domain-level object for a speaker brief, typically used in the application layer and exposed through API responses. It provides a standardized and user-friendly representation of a brief.
 *
 * It is used to provide a consistent, `camelCase` representation of a speaker brief for frontend consumption and internal application logic. This approach decouples the application's data model from the raw database schema, improving readability and adherence to common JavaScript/TypeScript coding styles.
 *
 * Important implementation details:
 * - Property names use `camelCase`, which is standard for JavaScript/TypeScript applications.
 * - It mirrors the structure of `SpeakerBriefRow` but with naming conventions adapted for the application layer.
 * - It includes `content` for the AI-generated brief and `editedContent` for professor's manual edits, following the same logic as `SpeakerBriefRow` for content prioritization (i.e., `editedContent` is preferred when present).
 * - This interface is typically returned by API endpoints, such as `GET /api/sessions/[id]/brief`, to provide brief data to clients.
 */
export interface SpeakerBrief {
  id: string
  sessionId: string
  userId: string
  /** The AI-generated brief content. */
  content: SpeakerBriefContent
  /**
   * Professor's manual edits; null if unchanged since generation.
   * Export routes prefer this over `content` when non-null.
   */
  editedContent: SpeakerBriefContent | null
  createdAt: string
  updatedAt: string
}
