/**
 * @file briefText.ts
 * Exports a SpeakerBriefContent object as a plain-text string.
 *
 * Called by: app/api/sessions/[id]/brief/download/route.ts (?format=text)
 *
 * No external library required — this is a pure string builder. The output is
 * formatted with uppercase section headers and dash-prefixed list items so it
 * reads cleanly when pasted into an email or copied to a notes app.
 *
 * Section order mirrors the PDF layout in lib/export/briefPdf.ts:
 *   1. Header block (speaker name, course, date, student count)
 *   2. What Students Care About
 *   3. Top Themes
 *   4. Suggested Talking Points
 *   5. Class Context
 *   6. What to Expect
 *
 * @see lib/export/briefPdf.ts for the branded PDF variant
 * @see lib/ai/speakerBrief.ts for the agent that generates SpeakerBriefContent
 */

import type { SpeakerBriefContent } from '@/types'

/**
 * Formats a SpeakerBriefContent object as a plain-text string suitable for
 * email copy-paste or download as a .txt file.
 *
 * @param content - The brief data generated by lib/ai/speakerBrief.ts
 * @returns       - Multi-line string with section headers and newline-separated items
 */
/**
 * Formats a SpeakerBriefContent object into a plain-text string.
 *
 * It is used to create a simple, human-readable version of the speaker brief, suitable for direct copy-pasting into emails, displaying in basic text viewers, or downloading as a .txt file, ensuring broad compatibility and ease of sharing without requiring special rendering.
 *
 * The function constructs an array of strings, `lines`, by iteratively adding formatted header information, narrative content, top themes (prefixed with '—'), numbered suggested talking points, and class context details. Each section is clearly demarcated with headers and newlines for readability. Finally, it joins all accumulated lines with newline characters to form a single multi-line string.
 */
export function formatBriefAsText(content: SpeakerBriefContent): string {
  const lines: string[] = []

  lines.push(`SPEAKER PREP BRIEF: ${content.header.speakerName}`)
  lines.push(`${content.header.courseLabel} — ${content.header.date}`)
  lines.push(`${content.header.studentCount} student submissions analyzed`)
  lines.push('')
  lines.push('---')
  lines.push('')

  lines.push('WHAT STUDENTS CARE ABOUT')
  lines.push(content.narrative)
  lines.push('')

  lines.push('TOP THEMES')
  for (const theme of content.topThemes) {
    lines.push(`— ${theme.title}: ${theme.description}`)
  }
  lines.push('')

  lines.push('SUGGESTED TALKING POINTS')
  content.talkingPoints.forEach((tp, i) => {
    lines.push(`${i + 1}. ${tp.point} — ${tp.rationale}`)
  })
  lines.push('')

  lines.push('CLASS CONTEXT')
  lines.push(content.classContext)
  lines.push('')

  lines.push('WHAT TO EXPECT')
  lines.push(content.whatToExpect)

  return lines.join('\n')
}
