/**
 * @file docx.ts
 * Exports a session's AI-generated interview sheet as a DOCX document.
 *
 * Called by: app/api/sessions/[id]/download/route.ts (?format=docx)
 *            app/api/shared/[token]/download/route.ts
 *
 * Library: docx — builds Office Open XML documents in Node.js using a
 * class-based builder API (Document, Paragraph, TextRun). No browser required.
 *
 * Input:  raw AI markdown output string + speaker name
 * Output: DOCX as a Node.js Buffer, ready to stream as
 *         application/vnd.openxmlformats-officedocument.wordprocessingml.document
 *
 * The local parseOutput() mirrors lib/parse/parseQuestions.ts#parseSections;
 * kept local to keep the export pipeline self-contained.
 */

import { Document, Packer, Paragraph, TextRun } from 'docx'

/** Internal question shape for the DOCX rendering pipeline. */
/**
 * Internal question shape for the DOCX rendering pipeline.
 *
 * What it does: Defines the structure for a student question, including its type (primary/backup), the question text, and its attribution.
 * Why it is used: To represent individual student questions consistently within the application's data model, specifically for processing and rendering into a DOCX document.
 * Important implementation details: Contains `label` (e.g., "Primary", "Backup"), `text` (the actual question), and `attribution` (the source or context of the question).
 */
interface Question {
  label: string
  text: string
  attribution: string
}

/** Internal section shape for the DOCX rendering pipeline. */
/**
 * Internal section shape for the DOCX rendering pipeline.
 *
 * What it does: Defines the structure for a logical section within the guest speaker interview sheet, typically comprising a title and potentially a primary and/or backup question.
 * Why it is used: To organize related questions under a thematic heading, mirroring the structural output generated by the AI and facilitating the sequential construction of the DOCX document.
 * Important implementation details: Includes a `title` string and optional `primary` and `backup` properties, which are `Question` objects or `null` if no question exists for that category within the section.
 */
interface Section {
  title: string
  primary: Question | null
  backup: Question | null
}

/**
 * Parses the AI markdown output into sections with primary/backup questions.
 * Mirrors the logic in lib/parse/parseQuestions.ts#parseSections.
 */
/**
 * Parses the AI markdown output into structured sections, each containing a title and associated primary/backup questions.
 *
 * What it does: Takes a raw markdown string, which is the AI's output, and transforms it into an array of `Section` objects.
 * Why it is used: To convert unstructured text output into a programmatically accessible and structured data format that can be easily iterated over and rendered into a DOCX document. This decouples the parsing logic from the document assembly.
 * Important implementation details:
 * - It processes the input line by line.
 * - Uses regular expressions to identify section titles (e.g., `***1. Section Title***`) and question lines (e.g., `**Primary:** Question text *(Attribution)*`).
 * - It skips blank lines and a specific "**Top Student Questions**" header.
 * - The parsing logic mirrors that found in `lib/parse/parseQuestions.ts#parseSections` to ensure consistent interpretation of AI output.
 */
function parseOutput(output: string): Section[] {
  const sections: Section[] = []
  let current: Section | null = null

  for (const raw of output.split('\n')) {
    const line = raw.trim()
    if (!line || line === '**Top Student Questions**') continue

    const titleMatch = line.match(/^\*{3}(\d+\.\s+.+?)\*{3}$/)
    if (titleMatch) {
      if (current) sections.push(current)
      current = { title: titleMatch[1], primary: null, backup: null }
      continue
    }

    const qMatch = line.match(/^\*\*(Primary|Backup):\*\*\s+(.*?)\s*\*\(([^)]+)\)\*\s*$/)
    if (qMatch && current) {
      const q: Question = { label: qMatch[1], text: qMatch[2], attribution: qMatch[3] }
      if (q.label === 'Primary') current.primary = q
      else current.backup = q
    }
  }

  if (current) sections.push(current)
  return sections
}

/**
 * Builds a single DOCX Paragraph for a Primary or Backup question.
 * Uses mixed TextRun styles: bold label, plain body, italic attribution.
 * `spacing.before/after` values are in twentieths of a point (twips).
 */
/**
 * Builds a single DOCX Paragraph for a Primary or Backup question.
 *
 * What it does: Creates a `Paragraph` object using the `docx` library, formatted specifically to display a single student question with distinct styles for its label, text, and attribution.
 * Why it is used: To encapsulate the styling and construction logic for individual question paragraphs, ensuring consistency and reusability throughout the DOCX generation process. This simplifies the `buildDocxContent` function by abstracting formatting details.
 * Important implementation details:
 * - It takes a `Question` object as input.
 * - Uses multiple `TextRun` elements within the `Paragraph` to apply different formatting: bold for the label, plain for the question text, and italics for the attribution.
 * - `spacing.before` and `spacing.after` values are set to `80` (twips) to provide consistent vertical separation between questions.
 */
function questionParagraph(q: Question): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({ text: `${q.label}: `, bold: true }),
      new TextRun({ text: q.text + ' ' }),
      new TextRun({ text: `(${q.attribution})`, italics: true }),
    ],
    spacing: { before: 80, after: 80 },
  })
}

/**
 * Assembles the full array of DOCX Paragraph nodes for a session interview sheet,
 * including title, subtitle, section headers, and all question paragraphs.
 */
/**
 * Assembles the full array of DOCX Paragraph nodes for a session interview sheet.
 *
 * What it does: Coordinates the creation of all `Paragraph` objects that constitute the main body of the guest speaker interview sheet, from static headers to dynamically generated section titles and questions.
 * Why it is used: To centralize the content layout and structure definition for the DOCX document. It acts as an orchestrator, combining parsed data with predefined document elements and styles to produce a complete list of paragraphs for the document.
 * Important implementation details:
 * - It first adds fixed introductory paragraphs, including the course name ("MGMT 305") and the guest speaker's name in the header.
 * - Calls `parseOutput` to get the structured `Section` data from the raw AI markdown.
 * - Iterates through each `Section`, adding a bold and italicized section title paragraph.
 * - For each section, it conditionally calls `questionParagraph` to add the primary and/or backup questions if they exist.
 * - Applies specific font sizes (e.g., 36 for main title, 24 for subtitle, 22 for section/category headers) and spacing (in twips) to different elements for visual hierarchy.
 */
function buildDocxContent(output: string, speakerName: string): Paragraph[] {
  const children: Paragraph[] = []

  children.push(new Paragraph({
    children: [new TextRun({ text: 'MGMT 305', bold: true, size: 36 })],
    spacing: { after: 80 },
  }))

  children.push(new Paragraph({
    children: [new TextRun({ text: `Guest Speaker Interview Sheet — ${speakerName}`, size: 24 })],
    spacing: { after: 320 },
  }))

  children.push(new Paragraph({
    children: [new TextRun({ text: 'Top Student Questions', bold: true, size: 22 })],
    spacing: { after: 240 },
  }))

  for (const section of parseOutput(output)) {
    children.push(new Paragraph({
      children: [new TextRun({ text: section.title, bold: true, italics: true, size: 22 })],
      spacing: { before: 160, after: 80 },
    }))

    if (section.primary) children.push(questionParagraph(section.primary))
    if (section.backup) children.push(questionParagraph(section.backup))
  }

  return children
}

/**
 * Generates a DOCX buffer for the session interview sheet.
 *
 * @param output      - Raw AI markdown output from the session (sessions.output column)
 * @param speakerName - Guest speaker name displayed in the document header
 * @returns           - DOCX as a Node.js Buffer, ready to stream as a Word document
 */
/**
 * Generates a DOCX buffer for the session interview sheet.
 *
 * What it does: This is the public entry point for creating the final Word document. It takes the AI markdown output and the speaker's name, then returns a promise that resolves to a Node.js `Buffer` containing the DOCX file.
 * Why it is used: To provide a high-level, convenient interface for consumers to generate a guest speaker interview sheet without needing to understand the underlying DOCX library details or content assembly logic. It abstracts the entire document generation process.
 * Important implementation details:
 * - It's an `async` function, as the `Packer.toBuffer` operation is asynchronous.
 * - It creates a new `Document` object from the `docx` library.
 * - It calls `buildDocxContent` to retrieve the fully structured array of `Paragraph` objects that form the document's body.
 * - The content is placed within a single `section` of the `Document`.
 * - `Packer.toBuffer(doc)` is used to serialize the `Document` object into a binary `Buffer`, which can then be streamed or saved as a `.docx` file.
 */
export async function generateDocx(output: string, speakerName: string): Promise<Buffer> {
  const doc = new Document({
    sections: [{ properties: {}, children: buildDocxContent(output, speakerName) }],
  })
  return Packer.toBuffer(doc)
}
