/**
 * @file storyDocx.ts
 * Exports a SemesterStory as a DOCX document using the `docx` library.
 *
 * Called by: app/api/stories/[id]/download/route.ts (?format=docx)
 *
 * Library: docx — class-based Office Open XML builder. No browser required.
 *
 * Document structure:
 *   1. Title page  (story title centered, "A Semester Narrative" subtitle, generated date)
 *   2. Content sections  (one HEADING_1 + body paragraphs per story section)
 *      — separated from the title page by an explicit PageBreak before section 0
 *
 * Section body text is split on double newlines to create discrete Paragraph nodes,
 * preserving the narrative structure generated by lib/ai/storyAgent.ts.
 *
 * Page margins are set to 1440 twips (1 inch) on all sides via the section properties.
 * Line spacing is 360 twips (double-spaced) for comfortable reading of narrative text.
 *
 * PURPLE (#542785) is used as the heading color to match the branded PDF variant.
 *
 * Input:  SemesterStory (generated by lib/ai/storyAgent.ts, stored in semester_stories table)
 * Output: DOCX as a Node.js Buffer, ready to stream as
 *         application/vnd.openxmlformats-officedocument.wordprocessingml.document
 *
 * @see lib/export/storyPdf.ts for the branded PDF variant of the same story
 * @see types/index.ts for the SemesterStory type definition
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
  HeadingLevel,
  PageBreak,
} from 'docx'
import type { SemesterStory } from '@/types'

/** Builds the centered, large title paragraph for the story cover. */
/**
 * Builds a Paragraph object for the main story title on the cover page.
 *
 * What it does: Creates a centered, large, bold, and purple-colored paragraph suitable for a document title.
 * Why it is used: To prominently display the primary title of the semester narrative at the very beginning of the document.
 * Important implementation details: It uses `HeadingLevel.TITLE` for semantic structure, `AlignmentType.CENTER` for centering, a large font size (52), bold styling, and a specific brand purple color (`542785`). Includes `spacing.after` for visual separation from subsequent elements.
 */
function titleParagraph(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text, bold: true, size: 52, color: '542785' })],
    spacing: { after: 200 },
  })
}

/** Builds the centered italic subtitle (e.g. "A Semester Narrative"). */
/**
 * Builds a Paragraph object for a centered, italic subtitle.
 *
 * What it does: Generates a paragraph formatted as a secondary title, often used for a descriptive phrase like "A Semester Narrative."
 * Why it is used: To provide additional context or a descriptive tag line for the story on the cover page, presented in a less prominent style than the main title.
 * Important implementation details: It uses `AlignmentType.CENTER` for centering, italic text, a medium font size (24), and a muted gray color (`666666`). Includes `spacing.after` for visual separation.
 */
function subtitleParagraph(text: string): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text, size: 24, color: '666666', italics: true })],
    spacing: { after: 100 },
  })
}

/** Builds the centered muted date line on the cover page. */
/**
 * Builds a Paragraph object for the centered muted date line on the cover page.
 *
 * What it does: Creates a paragraph to display the generation date of the document.
 * Why it is used: To provide metadata indicating when the document was produced, typically appearing below the title and subtitle on the cover page.
 * Important implementation details: It uses `AlignmentType.CENTER` for centering, a smaller font size (20), and a light gray color (`999999`). It includes a substantial `spacing.after` value to create significant vertical space, effectively separating the cover page content from the main story sections or a page break.
 */
function dateParagraph(text: string): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text, size: 20, color: '999999' })],
    spacing: { after: 600 },
  })
}

/** Builds a HEADING_1 paragraph for a story section title, styled in PURPLE. */
/**
 * Builds a Paragraph object for a story section title, styled as a HEADING_1.
 *
 * What it does: Generates a paragraph intended for major section titles within the story content.
 * Why it is used: To clearly delineate different parts of the narrative, improving the document's structure and readability for the user. It helps readers navigate through the story.
 * Important implementation details: It utilizes `HeadingLevel.HEADING_1` for hierarchical structure, bold styling, a specific font size (28), and the brand purple color (`542785`). It includes `spacing.before` and `spacing.after` to provide clear vertical spacing around each section heading.
 */
function sectionHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text, bold: true, size: 28, color: '542785' })],
    spacing: { before: 360, after: 200 },
  })
}

/** Builds a double-spaced body paragraph for story narrative text. */
/**
 * Builds a Paragraph object for story narrative body text, styled with double-spacing.
 *
 * What it does: Creates a paragraph specifically for the main textual content of the story.
 * Why it is used: To present the core narrative content of each story section in a readable and consistent format within the generated Word document.
 * Important implementation details: It sets a standard font size (22) and crucially applies double-spacing (`line: 360`) to enhance readability, a common requirement for academic or formal documents. It also includes `spacing.after` for clear separation between consecutive body paragraphs.
 */
function bodyParagraph(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, size: 22 })],
    spacing: { after: 160, line: 360 },
  })
}

/**
 * Generates a DOCX buffer for a semester narrative story.
 *
 * Each story section's body is split on double newlines to produce individual
 * body paragraphs. A PageBreak is inserted before the first section so that the
 * cover title page and content sections start on separate pages.
 *
 * @param story - The SemesterStory object from the `semester_stories` table.
 * @returns     - DOCX as a Node.js Buffer, ready to stream as a Word document.
 *
 * @usedBy app/api/stories/[id]/download/route.ts (?format=docx)
 */
/**
 * Generates a complete DOCX document as a Node.js Buffer from a `SemesterStory` object.
 *
 * What it does: This is the primary function responsible for taking structured story data and converting it into a fully formatted Microsoft Word document.
 * Why it is used: It serves as the core export mechanism, allowing users to download their semester narratives in a widely compatible and editable document format.
 * Important implementation details:
 * - It constructs the cover page using helper functions (`titleParagraph`, `subtitleParagraph`, `dateParagraph`).
 * - It iterates through each `story.section`, adding a `PageBreak` before the very first section to ensure the cover page stands alone.
 * - Each section's `body` text is split by double newlines (`/\n\n+/`) to create individual paragraphs, which are then formatted using `bodyParagraph`.
 * - The document is configured with standard 1-inch (1440 twips) page margins.
 * - It leverages the `docx` library's `Packer.toBuffer` method to convert the in-memory `Document` object into a `Buffer`, ready for streaming or saving.
 * - The function handles date formatting for the cover page.
 */
export async function generateStoryDocx(story: SemesterStory): Promise<Buffer> {
  const date = new Date(story.createdAt).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })

  const children: Paragraph[] = [
    titleParagraph(story.title),
    subtitleParagraph('A Semester Narrative'),
    dateParagraph(`Generated ${date}`),
  ]

  story.sections.forEach((section, i) => {
    // Page break before first section (after title page content)
    if (i === 0) {
      children.push(
        new Paragraph({
          children: [new PageBreak()],
        })
      )
    }

    children.push(sectionHeading(section.title))

    const paragraphs = section.body.split(/\n\n+/).filter(Boolean)
    for (const text of paragraphs) {
      children.push(bodyParagraph(text.trim()))
    }
  })

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        children,
      },
    ],
  })

  const buffer = await Packer.toBuffer(doc)
  return Buffer.from(buffer)
}
