/**
 * @file parseQuestions.ts
 * Parses the AI-generated markdown output into structured question data.
 *
 * Called by:
 *   - components/session/OutputPreview.tsx   (renders the questions tab)
 *   - lib/export/pdf.ts and lib/export/docx.ts (export rendering)
 *   - components/session/DebriefPanel.tsx    (debrief form question list)
 *
 * The xAI model outputs a 10-section markdown format defined in lib/ai/prompt.ts.
 * Each section follows this template:
 *
 *   ***N. Theme Title***
 *   **Primary:** Question text *(Student Name)*
 *   **Backup:** Question text *(Student Name)*
 *
 * These two functions parse that format without coupling to the rendering layer.
 */

/** A single question entry with its theme context, for use in the debrief form. */
/**
 * Represents a single question parsed from the AI output. 
 *
 * What it does: This interface defines the structure for an individual question, including its associated theme, its role (primary or backup), the question text itself, and the attribution for the question.
 * Why it is used: It provides a standardized data structure for individual questions, facilitating their storage, processing, and display in various parts of the application, such as feedback forms or question lists.
 * Important implementation details: It includes `themeTitle` to link the question back to its originating section and `role` ('primary' or 'backup') to distinguish its importance within a theme.
 */
export interface ParsedQuestion {
  themeTitle: string
  role: 'primary' | 'backup'
  text: string
  attribution: string
}

/**
 * A single theme section with its primary and backup question.
 * Used by the OutputPreview component and the PDF/DOCX export renderers.
 */
/**
 * A single theme section with its primary and backup question.
 *
 * What it does: This interface defines a structure to represent a distinct theme section, which encompasses a title for the theme, and optionally, a primary and a backup question related to that theme.
 * Why it is used: It serves as an intermediate, structured representation of the parsed AI output, grouping related primary and backup questions under a common thematic title. It is specifically used by components like the `OutputPreview` component and various PDF/DOCX export renderers that require this grouped structure.
 * Important implementation details: Each question within a section (primary or backup) is an object containing `label`, `text`, and `attribution`. These can be `null` if a corresponding question is not present for a given section.
 */
export interface ParsedSection {
  title: string
  primary: { label: string; text: string; attribution: string } | null
  backup: { label: string; text: string; attribution: string } | null
}

/**
 * Parses the full AI markdown output string into an ordered array of sections,
 * each with its primary and backup question.
 *
 * Parsing is line-by-line and state-machine-based:
 *   - Lines matching `***N. Title***` open a new section.
 *   - Lines matching `**Primary:** text *(Name)*` fill the primary slot.
 *   - Lines matching `**Backup:** text *(Name)*` fill the backup slot.
 *   - All other lines (narrative text, blank lines) are ignored.
 *
 * Returns an empty array if the output does not conform to the expected format.
 */
/**
 * Parses the full AI markdown output string into an ordered array of sections, each with its primary and backup question.
 *
 * What it does: This function takes a raw markdown string generated by the AI as input and transforms it into a structured array of `ParsedSection` objects. Each section represents a thematic grouping with its main and supplementary questions.
 * Why it is used: It is the core parsing logic responsible for converting the AI's free-form text output into a machine-readable and application-consumable data model. This structured output is essential for display, further processing, and export functionalities.
 * Important implementation details: Parsing is performed line-by-line using a state-machine-based approach. Regular expressions are used to identify section titles (e.g., `***N. Title***`) and question lines (e.g., `**Primary:** text *(Name)*`). Any lines that do not match these specific patterns (e.g., narrative text, blank lines, or the initial header) are ignored. The function returns an empty array if the input string does not conform to the expected markdown format, indicating a parsing failure. It maintains a `current` section state to build each section before pushing it to the final array.
 */
export function parseSections(output: string): ParsedSection[] {
  const sections: ParsedSection[] = []
  let current: ParsedSection | null = null

  for (const raw of output.split('\n')) {
    const line = raw.trim()
    if (!line || line === '**Top Student Questions**') continue

    // Section title: ***N. Theme Title***
    const titleMatch = line.match(/^\*{3}(\d+\.\s+.+?)\*{3}$/)
    if (titleMatch) {
      if (current) sections.push(current)
      current = { title: titleMatch[1], primary: null, backup: null }
      continue
    }

    // Question line: **Primary:** text *(Attribution)*
    const qMatch = line.match(/^\*\*(Primary|Backup):\*\*\s+(.*?)\s*\*\(([^)]+)\)\*\s*$/)
    if (qMatch && current) {
      const q = { label: qMatch[1], text: qMatch[2], attribution: qMatch[3] }
      if (q.label === 'Primary') current.primary = q
      else current.backup = q
    }
  }

  if (current) sections.push(current)
  return sections
}

/**
 * Flattens the parsed sections into a simple list of questions.
 *
 * Used by DebriefPanel to render a question-by-question feedback form.
 * Each question carries its `themeTitle` so it can be grouped in the UI.
 */
/**
 * Flattens the parsed sections into a simple list of questions.
 *
 * What it does: This function first parses a given AI markdown output string into themed sections and then transforms that section-based structure into a flat, one-dimensional array of individual `ParsedQuestion` objects.
 * Why it is used: It is primarily used by components like `DebriefPanel` that require a simple, linear list of questions, such as for rendering a question-by-question feedback form where the hierarchical section grouping is not immediately necessary.
 * Important implementation details: It internally leverages the `parseSections` function to handle the initial structural parsing. It then iterates through the resulting `ParsedSection` array, extracting both primary and backup questions and creating a `ParsedQuestion` object for each, ensuring that each question carries its `themeTitle` and `role` ('primary' or 'backup') for easier grouping and identification in the UI.
 */
export function parseQuestionsFromOutput(output: string): ParsedQuestion[] {
  const sections = parseSections(output)
  const questions: ParsedQuestion[] = []

  for (const section of sections) {
    if (section.primary) {
      questions.push({
        themeTitle: section.title,
        role: 'primary',
        text: section.primary.text,
        attribution: section.primary.attribution,
      })
    }
    if (section.backup) {
      questions.push({
        themeTitle: section.title,
        role: 'backup',
        text: section.backup.text,
        attribution: section.backup.attribution,
      })
    }
  }

  return questions
}
