/**
 * lib/ai/speakerPortalPostSession.ts
 *
 * Generates the POST-SESSION feedback section for a guest speaker's portal.
 *
 * After the professor marks the session debrief as complete, this module is
 * triggered (fire-and-forget) to synthesize professor feedback, question-level
 * ratings, and anonymized student reflection themes into a warm thank-you
 * document that is published back to the speaker's portal.
 *
 * This is the second phase of the speaker portal lifecycle:
 *  1. Pre-session: lib/ai/speakerPortal.ts generates the preparation content.
 *  2. Post-session (this file): reads the completed debrief + student debrief
 *     analyses and appends a PostSessionFeedback object to the portal record.
 *
 * Data sources:
 *  - speaker_portals table: portal existence check, speaker name, and
 *    the target record for writing the result back
 *  - session_debriefs table: overall rating, question feedback array,
 *    professor's free-text feedback, and surprise moments notes
 *  - session_themes table: theme list for the session
 *  - student_debrief_analyses table: anonymized student reflection themes
 *    and summary generated by lib/ai/debriefReflectionAnalysis.ts
 *
 * Uses: lib/ai/geminiClient.ts, lib/db/speakerPortals.ts, lib/db/debriefs.ts
 * Called by: app/api/sessions/[id]/debrief/complete/route.ts (POST handler)
 * Persists to: speaker_portals table via lib/db/speakerPortals.ts (updatePostSessionFeedback)
 */

import { getGeminiClient, getGeminiModel } from '@/lib/ai/geminiClient'
import type { PostSessionFeedback, QuestionFeedback } from '@/types'
import { getSpeakerPortal, updatePostSessionFeedback } from '@/lib/db/speakerPortals'
import { getDebrief } from '@/lib/db/debriefs'
import { createAdminClient } from '@/lib/supabase/server'

/**
 * Constructs the Gemini prompt for post-session feedback generation.
 *
 * Builds a data section containing the overall session rating, topics that
 * resonated ("home run" questions), professor feedback, and optionally
 * anonymized student reflection themes. The tone instruction is deliberately
 * set to "thank-you note with substance" — NOT a performance review.
 *
 * Home run extraction: only QuestionFeedback entries with status === 'home_run'
 * are surfaced; all other statuses (flat, ok) are silently omitted so the
 * feedback stays positive and actionable for the speaker.
 *
 * @param params - Debrief data plus session themes and student reflection summary
 * @returns A fully-formed prompt string ready for Gemini content generation
 * @remarks
 * Only "home run" questions are surfaced in the feedback. Flat/mediocre questions
 * are intentionally omitted — the goal is a warm thank-you experience for the
 * speaker, not a performance debrief. The professor retains the full question
 * feedback detail in their own debrief record.
 */
function buildPostSessionPrompt(params: {
  speakerName: string
  overallRating: number
  questionsFeedback: QuestionFeedback[]
  speakerFeedback: string
  surpriseMoments: string
  themes: string[]
  studentReflectionThemes: string[]
  studentReflectionSummary: string | null
}): string {
  const {
    speakerName,
    overallRating,
    questionsFeedback,
    speakerFeedback,
    surpriseMoments,
    themes,
    studentReflectionThemes,
    studentReflectionSummary,
  } = params

  // Extract only the "home run" questions — topics that resonated most with the class.
  // Prefer questionText for specificity; fall back to themeTitle if the question text
  // isn't available (e.g., if the feedback was recorded at the theme level).
  const homeRuns = questionsFeedback.filter(q => q.status === 'home_run')
  const homeRunTopics = homeRuns.map(q => q.questionText ?? q.themeTitle ?? 'Unknown topic')

  let dataSection = `Speaker: ${speakerName}
Overall Session Rating: ${overallRating}/5

Session Themes:
${themes.map((t, i) => `${i + 1}. ${t}`).join('\n')}

Topics That Resonated Most (rated as "home run"):
${homeRunTopics.length > 0 ? homeRunTopics.map(t => `- ${t}`).join('\n') : '- No specific topics flagged'}

Professor Feedback: ${speakerFeedback || 'No specific feedback provided'}
Surprise Moments: ${surpriseMoments || 'None noted'}`

  // Include student reflection data only if at least one of the two optional
  // fields is populated. The analysis comes from student_debrief_analyses, which
  // may not exist yet if no students submitted debrief reflections.
  if (studentReflectionThemes.length > 0 || studentReflectionSummary) {
    dataSection += `

Student Reflections (anonymized):
${studentReflectionThemes.length > 0 ? `Themes: ${studentReflectionThemes.join(', ')}` : ''}
${studentReflectionSummary ? `Summary: ${studentReflectionSummary}` : ''}`
  }

  return `You are writing a warm, appreciative post-session feedback section for a guest speaker's preparation portal.

The speaker has already visited the class and this feedback shows them the impact of their session. This should feel like a thank-you note with substance — NOT a performance review or report card.

Data:
---
${dataSection}
---

Generate a JSON object with EXACTLY this structure:

{
  "overallRating": ${overallRating},
  "topicsResonated": ["string — 3-5 specific topics or themes that landed particularly well with the class"],
  "studentHighlights": "string — A 2-3 sentence anonymized synthesis of how students responded to the session. What surprised them? What stuck with them? Frame positively and warmly. Never use student names.",
  "professorNotes": "string — A 1-2 sentence synthesis of the professor's observations about the session. If no feedback was provided, write a brief positive note about the session.",
  "narrative": "string — A warm 3-4 sentence wrap-up paragraph addressed to the speaker. Thank them, highlight the lasting impact, and express what made this session special. Write as: '${speakerName}, your session...'"
}

Rules:
- NEVER include student names or identifiable information
- The tone must be warm, grateful, and substantive — like a heartfelt thank-you note
- Ground everything in the data provided; do not fabricate details
- Return ONLY valid JSON. No markdown fences, no explanation text.`
}

/**
 * Generates warm, appreciative post-session feedback for a guest speaker.
 *
 * Calls Gemini with the professor's debrief data (rating, question feedback,
 * comments, surprise moments) and optionally anonymized student reflection
 * themes to produce a PostSessionFeedback JSON document containing:
 *  - overallRating: the session rating as-is (passed through, not AI-generated)
 *  - topicsResonated: 3-5 topics that landed well
 *  - studentHighlights: anonymized synthesis of how students responded
 *  - professorNotes: synthesis of professor observations
 *  - narrative: a warm, personalized wrap-up paragraph addressed to the speaker
 *
 * The system instruction enforces an appreciative tone ("thank-you note with
 * substance") and prohibits any student names or identifiable information.
 *
 * This function is the lower-level primitive; prefer `generateAndPublishPostSessionFeedback`
 * for the full fire-and-forget pipeline that fetches data and writes back to DB.
 *
 * @param params - Debrief data and anonymized student reflection context
 * @returns Parsed PostSessionFeedback JSON object
 * @remarks
 * This is the pure AI generation primitive. It has no DB dependencies and can
 * be called independently for testing or if the orchestration logic needs to be
 * restructured. The `generateAndPublishPostSessionFeedback` function is the
 * recommended entry point for production callers.
 * @see generateAndPublishPostSessionFeedback — the full pipeline that fetches data and persists
 */
export async function generatePostSessionFeedback(params: {
  speakerName: string
  overallRating: number
  questionsFeedback: QuestionFeedback[]
  speakerFeedback: string
  surpriseMoments: string
  themes: string[]
  studentReflectionThemes: string[]
  studentReflectionSummary: string | null
}): Promise<PostSessionFeedback> {
  // Uses: lib/ai/geminiClient.ts
  const ai = getGeminiClient()
  const model = getGeminiModel()

  const response = await ai.models.generateContent({
    model,
    contents: buildPostSessionPrompt(params),
    config: {
      systemInstruction:
        'You are writing warm, appreciative post-session feedback for a guest speaker. Always respond with valid JSON only. Never include student names or identifiable information.',
      // Force JSON response to avoid markdown fences or prose wrapping the output
      responseMimeType: 'application/json',
    },
  })

  // response.text is the raw JSON string; trim and parse directly
  const raw = (response.text ?? '').trim()
  return JSON.parse(raw) as PostSessionFeedback
}

/**
 * Fire-and-forget orchestrator: fetches all required data, generates post-session
 * feedback, and persists it back to the speaker portal record.
 *
 * This is the top-level entry point called from the debrief completion handler.
 * It silently short-circuits if the session has no portal (the professor may
 * never have generated one) or if the debrief is not yet marked complete.
 *
 * Orchestration steps:
 *  1. Guard: check a portal exists for this session (speaker_portals table)
 *  2. Guard: confirm debrief status === 'complete' (session_debriefs table)
 *  3. Fetch ordered session themes from session_themes
 *  4. Fetch anonymized student debrief analysis from student_debrief_analyses
 *     (produced by lib/ai/debriefReflectionAnalysis.ts — may be absent)
 *  5. Resolve speaker name from the portal's content (editedContent takes priority
 *     over the original AI-generated content if the professor edited it)
 *  6. Call generatePostSessionFeedback to produce the AI feedback object
 *  7. Persist the result via updatePostSessionFeedback (speaker_portals table)
 *
 * This function is designed to be awaited in a non-blocking context (fire-and-forget).
 * Errors bubble up to the caller, which should handle them gracefully.
 *
 * @param sessionId - The session UUID for which to generate post-session feedback
 * @returns Promise<void> — this function is designed for fire-and-forget use
 * @remarks
 * The function uses `editedContent ?? content` when resolving the speaker name
 * so that professor-edited portals (where the name may have been corrected) don't
 * produce feedback addressed to the wrong person.
 * @see app/api/sessions/[id]/debrief/complete/route.ts — the POST handler that triggers this
 * @see lib/ai/debriefReflectionAnalysis.ts — generates the student_debrief_analyses row consumed here
 * @see lib/db/speakerPortals.ts — updatePostSessionFeedback writes the result back
 */
export async function generateAndPublishPostSessionFeedback(
  sessionId: string
): Promise<void> {
  // Guard: skip silently if no portal has been created for this session.
  // The professor may have skipped the portal generation step entirely.
  // Uses: lib/db/speakerPortals.ts
  const portal = await getSpeakerPortal(sessionId)
  if (!portal) return

  // Guard: only proceed if the debrief is complete.
  // An in-progress debrief does not yet have the final rating/feedback data needed.
  // Uses: lib/db/debriefs.ts
  const debrief = await getDebrief(sessionId)
  if (!debrief || debrief.status !== 'complete') return

  // Fetch ordered session themes to provide thematic context in the feedback.
  // Uses admin client to bypass RLS since this runs in a server-side background job.
  const supabase = createAdminClient()
  const { data: themeRows } = await supabase
    .from('session_themes')
    .select('theme_title')
    .eq('session_id', sessionId)
    .order('theme_number', { ascending: true })
  const themes = (themeRows ?? []).map(r => r.theme_title as string)

  // Fetch anonymized student debrief analysis if one has been generated.
  // This data comes from lib/ai/debriefReflectionAnalysis.ts and is stored in
  // the student_debrief_analyses table. It may be absent if no students submitted
  // reflections or if analysis hasn't run yet.
  const { data: studentDebriefRow } = await supabase
    .from('student_debrief_analyses')
    .select('analysis')
    .eq('session_id', sessionId)
    .maybeSingle()

  // Cast the JSONB analysis column to the expected shape; null-safe throughout
  const studentAnalysis = studentDebriefRow?.analysis as {
    reflection_themes?: Array<{ name: string }>
    summary?: string
  } | null

  // Prefer editedContent (professor-revised version) over original AI content
  // when resolving the speaker name, to avoid a mismatch if the name was corrected.
  const content = portal.editedContent ?? portal.content
  const speakerName = content.welcome.speakerName

  const feedback = await generatePostSessionFeedback({
    speakerName,
    overallRating: debrief.overallRating ?? 0,
    questionsFeedback: debrief.questionsFeedback ?? [],
    speakerFeedback: debrief.speakerFeedback ?? '',
    surpriseMoments: debrief.surpriseMoments ?? '',
    themes,
    // Map reflection_themes array of objects to a plain string array for the prompt
    studentReflectionThemes: (studentAnalysis?.reflection_themes ?? []).map(t => t.name),
    studentReflectionSummary: studentAnalysis?.summary ?? null,
  })

  // Persist the generated feedback back to the portal record.
  // Uses: lib/db/speakerPortals.ts
  await updatePostSessionFeedback(sessionId, feedback)
}
