/**
 * @file lib/ai/sqlAgent.ts
 *
 * Natural-language → SQL → plain-English answer agent for the analytics page.
 *
 * Professors can type free-form questions ("Which students submitted the most
 * questions this semester?") and get a readable answer derived from actual DB data.
 * This module implements the two-step pipeline:
 *   1. Gemini generates a SELECT query from the question + schema context
 *   2. The query runs against Supabase via the `execute_analytics_query` RPC
 *   3. Gemini converts the raw rows into a plain-English answer for the professor
 *
 * ## Security model
 * - Client-side regex guard (`assertReadOnly`) blocks obvious write keywords before
 *   the query reaches the database
 * - The `execute_analytics_query` Postgres function (SECURITY DEFINER) performs a
 *   second server-side validation and only allows SELECT statements
 * - The admin client is used for the RPC call because `execute_analytics_query`
 *   bypasses RLS by design (professors need read access across their data)
 *
 * ## Where it fits
 * - Called by: app/api/analytics/query/route.ts
 * - Uses: lib/ai/geminiClient.ts, lib/supabase/server.ts (admin client)
 * - The `execute_analytics_query` SQL function must exist in Supabase before
 *   this module can operate
 */

import { getGeminiClient, getGeminiModel } from '@/lib/ai/geminiClient'
import { createAdminClient } from '@/lib/supabase/server'

// ---------------------------------------------------------------------------
// Read-only SQL guard (client-side; DB fn also validates)
// ---------------------------------------------------------------------------

/**
 * Regex matching any SQL keyword that could modify data or schema.
 * Tested against the raw SQL string before it is sent to the database.
 * This is a defence-in-depth check — the DB-level RPC also validates.
 */
/**
 * Regex matching any SQL keyword that could modify data or schema.
 *
 * What it does: Defines a regular expression to identify SQL keywords that perform write operations or Data Definition Language (DDL) commands.
 * Why it is used: To implement a crucial client-side safety check. This regex helps prevent the accidental or malicious execution of non-SELECT queries before they even reach the database, serving as a primary defense-in-depth mechanism that complements server-side validation.
 * Important implementation details: It uses word boundaries (`\b`) to ensure whole keywords are matched and is case-insensitive (`i` flag) to catch variations like 'insert' or 'UPDATE'. It covers common DML (INSERT, UPDATE, DELETE, COPY) and DDL (DROP, CREATE, ALTER, TRUNCATE, GRANT, REVOKE) commands.
 */
const WRITE_KEYWORDS = /\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|GRANT|REVOKE|COPY)\b/i

/**
 * Throws if the generated SQL contains any write or DDL keywords.
 *
 * This client-side check runs before the query reaches Supabase, providing an
 * early rejection that produces a more informative error message than what the
 * database function would return. The DB function also validates — this is not
 * the only guard.
 *
 * @param sql - The raw SQL string generated by Gemini
 * @throws Error if any disallowed keyword is found
 */
/**
 * Throws if the generated SQL contains any write or DDL keywords.
 *
 * What it does: Validates a given SQL string to ensure it strictly contains only read-only operations (i.e., SELECT queries).
 * Why it is used: This client-side check runs before the query is sent to the Supabase database. It provides an early rejection point, producing a more immediate and informative error message to the user or developer than a generic database error would. This functions as a vital defense-in-depth layer; while the database-level RPC also validates the query, this client-side guard offers enhanced user experience and pre-empts potentially unsafe queries.
 * Important implementation details: It leverages the `WRITE_KEYWORDS` regular expression. If `WRITE_KEYWORDS.test(sql)` returns true, indicating a prohibited keyword, an `Error` is thrown with a descriptive message specific to analytics queries.
 */
function assertReadOnly(sql: string): void {
  if (WRITE_KEYWORDS.test(sql)) {
    throw new Error('Only SELECT queries are permitted in analytics.')
  }
}

// ---------------------------------------------------------------------------
// Schema context
// ---------------------------------------------------------------------------

/**
 * Static schema description injected into every SQL-generation prompt.
 *
 * This gives Gemini the table and column definitions it needs to write correct
 * JOIN conditions, filter expressions, and aliases. Kept deliberately minimal —
 * only the four tables relevant to analytics queries are described.
 *
 * Important notes embedded in the schema:
 * - `student_name` is stored in "FirstName L." format (partial name matching guidance)
 * - `semester_id = NULL` means the session is unassigned
 * - `theme_number` is 1-based within a session
 */
/**
 * Static schema description injected into every SQL-generation prompt.
 *
 * What it does: Provides a concise, static description of the relevant PostgreSQL database schema, including table and column definitions.
 * Why it is used: To furnish the Gemini AI model with the essential structural context it needs to accurately generate SQL queries from natural language questions. This schema description enables Gemini to understand table relationships, column types, and specific data formats, which is crucial for writing correct JOIN conditions, filter expressions, and appropriate aliases.
 * Important implementation details: The schema is deliberately kept minimal, describing only the four tables (`semesters`, `sessions`, `student_submissions`, `session_themes`) that are pertinent to analytics queries. Important domain-specific notes and rules are embedded within the description, such as the `student_name` format ("FirstName L."), the meaning of `semester_id = NULL` (unassigned sessions), and the 1-based indexing of `theme_number`. Explicit rules for the AI, like "Only generate SELECT queries" and "Always qualify table names", are also included.
 */
const SCHEMA_CONTEXT = `
You have read-only access to a PostgreSQL database for a university professor tool called MGMT 305.
Professors upload student question submissions for guest speaker sessions; the AI synthesizes them.

Tables available to you:

  semesters (
    id           UUID PRIMARY KEY,
    user_id      UUID,           -- professor's user ID
    name         TEXT,           -- e.g. "Spring 2026"
    start_date   DATE,
    end_date     DATE,
    status       TEXT,           -- 'active' or 'archived'
    created_at   TIMESTAMPTZ
  )

  sessions (
    id           UUID PRIMARY KEY,
    user_id      UUID,           -- professor's user ID
    speaker_name TEXT,           -- name of the guest speaker
    created_at   TIMESTAMPTZ,
    output       TEXT,           -- full AI-generated markdown output
    file_count   INTEGER,        -- number of student files processed
    semester_id  UUID REFERENCES semesters(id)  -- nullable; NULL = unassigned to any semester
  )

  student_submissions (
    id              UUID PRIMARY KEY,
    session_id      UUID REFERENCES sessions(id),
    student_name    TEXT,         -- "FirstName L." format, e.g. "Jake M."
    submission_text TEXT,         -- raw text of what the student submitted
    created_at      TIMESTAMPTZ
  )

  session_themes (
    id           UUID PRIMARY KEY,
    session_id   UUID REFERENCES sessions(id),
    theme_number INTEGER,          -- 1-based rank
    theme_title  TEXT,             -- e.g. "Leadership Under Pressure"
    created_at   TIMESTAMPTZ
  )

Rules:
- Only generate SELECT queries. Never INSERT, UPDATE, DELETE, or DROP anything.
- Always qualify table names (e.g. sessions.id, not just id) when joining.
- Return concise, readable column aliases in result sets.
- student_name is stored as "FirstName L." — use ILIKE '%Jake%' for partial first-name matching.
- session_themes.theme_number is 1-based ordering within a session.
- sessions.semester_id links to semesters. When the user asks about a specific semester, filter by sessions.semester_id. NULL semester_id means the session is unassigned to any semester.
`.trim()

/**
 * Builds the Gemini prompt that asks the model to generate a SQL SELECT query
 * from a natural language question.
 *
 * Instructs Gemini to return only raw SQL — no markdown fences, no trailing
 * semicolon — so the result can be used directly in the `assertReadOnly` check
 * and passed to the Supabase RPC without further transformation (beyond trimming).
 *
 * @param question - The professor's free-form analytics question
 * @returns The full SQL-generation prompt
 */
/**
 * Builds the Gemini prompt that asks the model to generate a SQL SELECT query
 * from a natural language question.
 *
 * What it does: Constructs the full prompt string that will be sent to the Gemini AI model to request the generation of a SQL SELECT query.
 * Why it is used: To precisely instruct Gemini on its task. It ensures the AI receives all necessary context (database schema, specific rules) and is explicitly directed to return only the raw SQL query, without any additional markdown formatting, explanations, or trailing semicolons. This simplifies post-processing of the AI's output.
 * Important implementation details: It prepends the `SCHEMA_CONTEXT` variable to provide the AI with the foundational knowledge of the database structure and associated rules. The prompt explicitly specifies that the AI should "Generate a single, read-only SQL SELECT query" and "Respond with ONLY the raw SQL query — no markdown fences, no explanation, no trailing semicolon" to ensure clean output.
 */
function buildSqlPrompt(question: string): string {
  return `${SCHEMA_CONTEXT}

Generate a single, read-only SQL SELECT query that answers this question:
"${question}"

Respond with ONLY the raw SQL query — no markdown fences, no explanation, no trailing semicolon.`
}

/**
 * Builds the Gemini prompt that converts raw database rows into a plain-English
 * answer for the professor.
 *
 * Provides both the original question and the executed SQL as context so Gemini
 * can map column names to meaningful phrases. The prompt explicitly forbids
 * repeating SQL or internal table names in the output, keeping the answer
 * approachable for non-technical users.
 *
 * @param question - The professor's original natural language question
 * @param sql - The SQL query that was executed (for Gemini's context)
 * @param rows - The raw result rows returned by the database
 * @returns The full answer-generation prompt
 */
/**
 * Builds the Gemini prompt that converts raw database rows into a plain-English
 * answer for the professor.
 *
 * What it does: Assembles the prompt string used to instruct the Gemini AI model to transform raw database query results into a human-readable, plain-English answer.
 * Why it is used: To bridge the gap between technical database output and user understanding. This prompt allows Gemini to synthesize the executed query, its results, and the original question into an easily digestible response for a non-technical user (the professor).
 * Important implementation details: It provides three key pieces of context to Gemini: the `question` (original natural language query), the `sql` (the executed query, for contextual understanding of column names and intent), and the `rows` (the raw JSON representation of the database results). The prompt explicitly forbids Gemini from repeating the SQL query or mentioning internal table names in its output, ensuring the answer remains approachable and free of technical jargon.
 */
function buildAnswerPrompt(question: string, sql: string, rows: unknown[]): string {
  return `A professor asked: "${question}"

The following SQL was run:
${sql}

The query returned ${rows.length} row(s):
${JSON.stringify(rows, null, 2)}

Write a clear, concise plain-English answer for the professor. Use bullet points if there are multiple items. Do not repeat the SQL or mention internal table names.`
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * The result returned to the client after a successful analytics query.
 * Both fields are surfaced in the UI — `answer` is shown to the professor,
 * while `sql` is available in a collapsible "View SQL" panel for transparency.
 */
/**
 * The result returned to the client after a successful analytics query.
 * Both fields are surfaced in the UI — `answer` is shown to the professor,
 * while `sql` is available in a collapsible "View SQL" panel for transparency.
 *
 * What it does: Defines the TypeScript interface for the structured data object returned by the `runAnalyticsQuery` function.
 * Why it is used: To provide a clear, type-safe contract for the output of the entire analytics pipeline. This standardization facilitates reliable data handling and consumption by the client-side UI, which expects both the human-friendly answer and the underlying SQL query for distinct display purposes.
 * Important implementation details: It consists of two string properties: `answer` (the plain-English natural language response generated by Gemini) and `sql` (the exact SQL SELECT query that was executed against the database).
 */
export interface AnalyticsResult {
  /** Plain-English answer generated by Gemini from the query results */
  answer: string
  /** The exact SQL SELECT query that was executed against the database */
  sql: string
}

/**
 * Runs a full natural-language → SQL → plain-English answer pipeline.
 *
 * Four-step flow:
 * 1. **SQL generation**: Gemini produces a SELECT query from the professor's question
 *    and the embedded schema context (`SCHEMA_CONTEXT`)
 * 2. **Read-only validation**: The generated SQL is checked for write keywords.
 *    Markdown fences and trailing semicolons are stripped before the check.
 * 3. **Query execution**: The SQL runs via the `execute_analytics_query` Supabase
 *    RPC (SECURITY DEFINER), which performs its own server-side SELECT validation
 * 4. **Answer generation**: Gemini converts the raw result rows into a professor-
 *    friendly plain-English response
 *
 * The `answer` and `sql` are both returned so the caller can display them
 * separately in the UI (answer prominently; SQL in a collapsible debug panel).
 *
 * Called by: app/api/analytics/query/route.ts
 * Uses: lib/ai/geminiClient.ts, lib/supabase/server.ts (admin client)
 *
 * @param question - The professor's free-form analytics question in plain English
 * @returns `{ answer, sql }` — the plain-English response and the executed SQL
 * @throws Error if the generated SQL contains write keywords or if the DB query fails
 */
/**
 * Runs a full natural-language → SQL → plain-English answer pipeline.
 *
 * What it does: Orchestrates the entire end-to-end process of taking a natural language question from a user, converting it into a SQL query, executing that query against the database, and then transforming the results back into a plain-English answer.
 * Why it is used: To provide a single, comprehensive public API (`export async function`) for the application to interact with the AI-powered analytics system. It encapsulates the complex, multi-step pipeline, simplifying its consumption by API routes or other parts of the codebase, ensuring consistency and security across the analytics feature.
 * Important implementation details: This function implements a four-step flow:
 * 1.  **SQL generation**: Utilizes Gemini (via `buildSqlPrompt`) to produce a `SELECT` query based on the user's question and the `SCHEMA_CONTEXT`.
 * 2.  **Read-only validation**: Performs a crucial client-side check (`assertReadOnly`) on the generated SQL to ensure it contains no write or DDL keywords. This happens after stripping any potential markdown fences or trailing semicolons from Gemini's raw output.
 * 3.  **Query execution**: The validated SQL is executed securely via the `execute_analytics_query` Supabase RPC. This RPC is a `SECURITY DEFINER` function in PostgreSQL, which performs its own server-side validation for `SELECT`-only queries.
 * 4.  **Answer generation**: Gemini is used again (via `buildAnswerPrompt`) to convert the raw database result rows into a professor-friendly, plain-English response.
 * The function returns an `AnalyticsResult` object containing both the `answer` and the `sql` for UI display. It also includes error handling for database failures and robust post-processing of Gemini's SQL output to ensure a clean query string.
 */
export async function runAnalyticsQuery(question: string): Promise<AnalyticsResult> {
  const ai = getGeminiClient()
  const model = getGeminiModel()

  // Step 1: generate SQL
  const sqlResponse = await ai.models.generateContent({
    model,
    contents: buildSqlPrompt(question),
    config: { systemInstruction: 'You are an expert PostgreSQL query writer. Output only raw SQL.' },
  })

  // Strip markdown fences and trailing semicolons — Gemini sometimes wraps output
  // in ```sql ... ``` blocks or adds a semicolon even when told not to
  const sql = (sqlResponse.text ?? '').trim()
    .replace(/^```(?:sql)?\s*/i, '')
    .replace(/\s*```$/, '')
    .replace(/;$/, '')
    .trim()

  // Step 2: validate read-only (client-side guard; DB RPC also validates)
  assertReadOnly(sql)

  // Step 3: execute via Supabase RPC (SECURITY DEFINER function, also validates SELECT-only)
  const supabase = createAdminClient()
  const { data, error } = await supabase.rpc('execute_analytics_query', { query_text: sql })
  if (error) throw new Error(`Query failed: ${error.message}`)

  // Normalise response to always be an array regardless of how many rows were returned
  const rows: unknown[] = Array.isArray(data) ? data : (data ? [data] : [])

  // Step 4: format natural language answer
  const answerResponse = await ai.models.generateContent({
    model,
    contents: buildAnswerPrompt(question, sql, rows),
    config: { systemInstruction: 'You are a helpful assistant summarising database query results for a professor.' },
  })

  const answer = (answerResponse.text ?? '').trim()

  return { answer, sql }
}
